#!/bin/sh

# Mini-script to run the different builds
#
# This script is expected to change as the product evolves
# to properly call the development scripts.

HELP=false
LINUX=false
WIN32=false
ISO=false

while test -n "$1"
do
	case "$1" in
	-h|--help) HELP=true;;
	--linux) LINUX=true;;
	--win32) WIN32=true;;
	--iso) ISO=true;;
	--all) LINUX=true; WIN32=true; ISO=true;;
	*) echo "Unknown option $1. Try --help"
	   exit 1;;
	esac
	shift
done

if $HELP
then
	echo "Use one of the following options to build what you need:"
	echo "   --linux      build debian, redhat, tarball packages"
	echo "   --win32      build win32 packages"
	echo "   --iso        build the .iso"
	echo "   --all        rebuild everything"
	exit 1;
fi


# Build Debian, RPM, tarball
if $LINUX
then
	dev/build --cd --debian --redhat --tarball --legacy-ui --all
fi

# Build Win32
if $WIN32
then
	dev/build --cd --win32 --legacy-ui --all
fi

# Build iso
if $ISO
then
	dev/build-iso
fi



