//===============================================================================
// Copyright (c) 2005-2013 by Made to Order Software Corporation
// 
// All Rights Reserved.
// 
// The source code in this file ("Source Code") is provided by Made to Order Software Corporation
// to you under the terms of the GNU General Public License, version 2.0
// ("GPL").  Terms of the GPL can be found in doc/GPL-license.txt in this distribution.
// 
// By copying, modifying or distributing this software, you acknowledge
// that you have read and understood your obligations described above,
// and agree to abide by those obligations.
// 
// ALL SOURCE CODE IN THIS DISTRIBUTION IS PROVIDED "AS IS." THE AUTHOR MAKES NO
// WARRANTIES, EXPRESS, IMPLIED OR OTHERWISE, REGARDING ITS ACCURACY,
// COMPLETENESS OR PERFORMANCE.
//===============================================================================



#include	"mo/mo_xml.h"


namespace molib
{

const char *	moXMLParser::g_html_dtd =

"<!--\n"
"    This is HTML 4.01 Strict DTD, which excludes the presentation \n"
"    attributes and elements that W3C expects to phase out as \n"
"    support for style sheets matures. Authors should use the Strict\n"
"    DTD when possible, but may use the Transitional DTD when support\n"
"    for presentation attribute and elements is required.\n"
"    \n"
"    HTML 4 includes mechanisms for style sheets, scripting,\n"
"    embedding objects, improved support for right to left and mixed\n"
"    direction text, and enhancements to forms for improved\n"
"    accessibility for people with disabilities.\n"
"\n"
"          Draft: $Date: 1999/12/24 23:37:49 $\n"
"\n"
"          Authors:\n"
"              Dave Raggett <dsr@w3.org>\n"
"              Arnaud Le Hors <lehors@w3.org>\n"
"              Ian Jacobs <ij@w3.org>\n"
"\n"
"    Further information about HTML 4.01 is available at:\n"
"\n"
"        http://www.w3.org/TR/1999/REC-html401-19991224\n"
"\n"
"\n"
"    The HTML 4.01 specification includes additional\n"
"    syntactic constraints that cannot be expressed within\n"
"    the DTDs.\n"
"\n"
"-->\n"
"<!--\n"
"    Typical usage:\n"
"\n"
"    <!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01//EN\"\n"
"            \"http://www.w3.org/TR/html4/strict.dtd\">\n"
"    <html>\n"
"    <head>\n"
"    ...\n"
"    </head>\n"
"    <body>\n"
"    ...\n"
"    </body>\n"
"    </html>\n"
"\n"
"    The URI used as a system identifier with the public identifier allows\n"
"    the user agent to download the DTD and entity sets as needed.\n"
"\n"
"    The FPI for the Transitional HTML 4.01 DTD is:\n"
"\n"
"        \"-//W3C//DTD HTML 4.01 Transitional//EN\"\n"
"\n"
"    This version of the transitional DTD is:\n"
"\n"
"        http://www.w3.org/TR/1999/REC-html401-19991224/loose.dtd\n"
"\n"
"    If you are writing a document that includes frames, use \n"
"    the following FPI:\n"
"\n"
"        \"-//W3C//DTD HTML 4.01 Frameset//EN\"\n"
"\n"
"    This version of the frameset DTD is:\n"
"\n"
"        http://www.w3.org/TR/1999/REC-html401-19991224/frameset.dtd\n"
"\n"
"    Use the following (relative) URIs to refer to \n"
"    the DTDs and entity definitions of this specification:\n"
"\n"
"    \"strict.dtd\"\n"
"    \"loose.dtd\"\n"
"    \"frameset.dtd\"\n"
"    \"HTMLlat1.ent\"\n"
"    \"HTMLsymbol.ent\"\n"
"    \"HTMLspecial.ent\"\n"
"\n"
"-->\n"
"\n"
"<!--================== Imported Names ====================================-->\n"
"<!-- Feature Switch for frameset documents -->\n"
"<!ENTITY % HTML.Frameset \"IGNORE\">\n"
"\n"
"<!ENTITY % ContentType \"CDATA\"\n"
"    -- media type, as per [RFC2045]\n"
"    -->\n"
"\n"
"<!ENTITY % ContentTypes \"CDATA\"\n"
"    -- comma-separated list of media types, as per [RFC2045]\n"
"    -->\n"
"\n"
"<!ENTITY % Charset \"CDATA\"\n"
"    -- a character encoding, as per [RFC2045]\n"
"    -->\n"
"\n"
"<!ENTITY % Charsets \"CDATA\"\n"
"    -- a space-separated list of character encodings, as per [RFC2045]\n"
"    -->\n"
"\n"
"<!ENTITY % LanguageCode \"NAME\"\n"
"    -- a language code, as per [RFC1766]\n"
"    -->\n"
"\n"
"<!ENTITY % Character \"CDATA\"\n"
"    -- a single character from [ISO10646] \n"
"    -->\n"
"\n"
"<!ENTITY % LinkTypes \"CDATA\"\n"
"    -- space-separated list of link types\n"
"    -->\n"
"\n"
"<!ENTITY % MediaDesc \"CDATA\"\n"
"    -- single or comma-separated list of media descriptors\n"
"    -->\n"
"\n"
"<!ENTITY % URI \"CDATA\"\n"
"    -- a Uniform Resource Identifier,\n"
"       see [URI]\n"
"    -->\n"
"\n"
"<!ENTITY % Datetime \"CDATA\" -- date and time information. ISO date format -->\n"
"\n"
"\n"
"<!ENTITY % Script \"CDATA\" -- script expression -->\n"
"\n"
"<!ENTITY % StyleSheet \"CDATA\" -- style sheet data -->\n"
"\n"
"\n"
"\n"
"<!ENTITY % Text \"CDATA\">\n"
"\n"
"\n"
"<!-- Parameter Entities -->\n"
"\n"
"<!ENTITY % head.misc \"SCRIPT|STYLE|META|LINK|OBJECT\" -- repeatable head elements -->\n"
"\n"
"<!ENTITY % heading \"H1|H2|H3|H4|H5|H6\">\n"
"\n"
"<!ENTITY % list \"UL | OL\">\n"
"\n"
"<!ENTITY % preformatted \"PRE\">\n"
"\n"
"\n"
"<!--================ Character mnemonic entities =========================-->\n"
"\n"
"<!ENTITY % HTMLlat1 PUBLIC\n"
"   \"-//W3C//ENTITIES Latin1//EN//HTML\"\n"
"   \"HTMLlat1.ent\">\n"
"%HTMLlat1;\n"
"\n"
"<!ENTITY % HTMLsymbol PUBLIC\n"
"   \"-//W3C//ENTITIES Symbols//EN//HTML\"\n"
"   \"HTMLsymbol.ent\">\n"
"%HTMLsymbol;\n"
"\n"
"<!ENTITY % HTMLspecial PUBLIC\n"
"   \"-//W3C//ENTITIES Special//EN//HTML\"\n"
"   \"HTMLspecial.ent\">\n"
"%HTMLspecial;\n"
"<!--=================== Generic Attributes ===============================-->\n"
"\n"
"<!ENTITY % coreattrs\n"
" \"id          ID             #IMPLIED  -- document-wide unique id --\n"
"  class       CDATA          #IMPLIED  -- space-separated list of classes --\n"
"  style       %StyleSheet;   #IMPLIED  -- associated style info --\n"
"  title       %Text;         #IMPLIED  -- advisory title --\"\n"
"  >\n"
"\n"
"<!ENTITY % i18n\n"
" \"lang        %LanguageCode; #IMPLIED  -- language code --\n"
"  dir         (ltr|rtl)      #IMPLIED  -- direction for weak/neutral text --\"\n"
"  >\n"
"\n"
"<!ENTITY % events\n"
" \"onclick     %Script;       #IMPLIED  -- a pointer button was clicked --\n"
"  ondblclick  %Script;       #IMPLIED  -- a pointer button was double clicked--\n"
"  onmousedown %Script;       #IMPLIED  -- a pointer button was pressed down --\n"
"  onmouseup   %Script;       #IMPLIED  -- a pointer button was released --\n"
"  onmouseover %Script;       #IMPLIED  -- a pointer was moved onto --\n"
"  onmousemove %Script;       #IMPLIED  -- a pointer was moved within --\n"
"  onmouseout  %Script;       #IMPLIED  -- a pointer was moved away --\n"
"  onkeypress  %Script;       #IMPLIED  -- a key was pressed and released --\n"
"  onkeydown   %Script;       #IMPLIED  -- a key was pressed down --\n"
"  onkeyup     %Script;       #IMPLIED  -- a key was released --\"\n"
"  >\n"
"\n"
"<!-- Reserved Feature Switch -->\n"
"<!ENTITY % HTML.Reserved \"IGNORE\">\n"
"\n"
"<!-- The following attributes are reserved for possible future use -->\n"
"<![ %HTML.Reserved; [\n"
"<!ENTITY % reserved\n"
" \"datasrc     %URI;          #IMPLIED  -- a single or tabular Data Source --\n"
"  datafld     CDATA          #IMPLIED  -- the property or column name --\n"
"  dataformatas (plaintext|html) plaintext -- text or html --\"\n"
"  >\n"
"]]>\n"
"\n"
"<!ENTITY % reserved \"\">\n"
"\n"
"<!ENTITY % attrs \"%coreattrs; %i18n; %events;\">\n"
"\n"
"\n"
"<!--=================== Text Markup ======================================-->\n"
"\n"
"<!ENTITY % fontstyle\n"
" \"TT | I | B | BIG | SMALL\">\n"
"\n"
"<!ENTITY % phrase \"EM | STRONG | DFN | CODE |\n"
"                   SAMP | KBD | VAR | CITE | ABBR | ACRONYM\" >\n"
"\n"
"<!ENTITY % special\n"
"   \"A | IMG | OBJECT | BR | SCRIPT | MAP | Q | SUB | SUP | SPAN | BDO\">\n"
"\n"
"<!ENTITY % formctrl \"INPUT | SELECT | TEXTAREA | LABEL | BUTTON\">\n"
"\n"
"<!-- %inline; covers inline or \"text-level\" elements -->\n"
"<!ENTITY % inline \"#PCDATA | %fontstyle; | %phrase; | %special; | %formctrl;\">\n"
"\n"
"<!ELEMENT (%fontstyle;|%phrase;) - - (%inline;)*>\n"
"<!ATTLIST (%fontstyle;|%phrase;)\n"
"  %attrs;                              -- %coreattrs, %i18n, %events --\n"
"  >\n"
"\n"
"<!ELEMENT (SUB|SUP) - - (%inline;)*    -- subscript, superscript -->\n"
"<!ATTLIST (SUB|SUP)\n"
"  %attrs;                              -- %coreattrs, %i18n, %events --\n"
"  >\n"
"\n"
"<!ELEMENT SPAN - - (%inline;)*         -- generic language/style container -->\n"
"<!ATTLIST SPAN\n"
"  %attrs;                              -- %coreattrs, %i18n, %events --\n"
"  %reserved;                   -- reserved for possible future use --\n"
"  >\n"
"\n"
"<!ELEMENT BDO - - (%inline;)*          -- I18N BiDi over-ride -->\n"
"<!ATTLIST BDO\n"
"  %coreattrs;                          -- id, class, style, title --\n"
"  lang        %LanguageCode; #IMPLIED  -- language code --\n"
"  dir         (ltr|rtl)      #REQUIRED -- directionality --\n"
"  >\n"
"\n"
"\n"
"<!ELEMENT BR - O EMPTY                 -- forced line break -->\n"
"<!ATTLIST BR\n"
"  %coreattrs;                          -- id, class, style, title --\n"
"  >\n"
"\n"
"<!--================== HTML content models ===============================-->\n"
"\n"
"<!--\n"
"    HTML has two basic content models:\n"
"\n"
"        %inline;     character level elements and text strings\n"
"        %block;      block-like elements e.g. paragraphs and lists\n"
"-->\n"
"\n"
"<!ENTITY % block\n"
"     \"P | %heading; | %list; | %preformatted; | DL | DIV | NOSCRIPT |\n"
"      BLOCKQUOTE | FORM | HR | TABLE | FIELDSET | ADDRESS\">\n"
"\n"
"<!ENTITY % flow \"%block; | %inline;\">\n"
"\n"
"<!--=================== Document Body ====================================-->\n"
"\n"
"<!ELEMENT BODY O O (%block;|SCRIPT)+ +(INS|DEL) -- document body -->\n"
"<!ATTLIST BODY\n"
"  %attrs;                              -- %coreattrs, %i18n, %events --\n"
"  onload          %Script;   #IMPLIED  -- the document has been loaded --\n"
"  onunload        %Script;   #IMPLIED  -- the document has been removed --\n"
"  >\n"
"\n"
"<!ELEMENT ADDRESS - - (%inline;)* -- information on author -->\n"
"<!ATTLIST ADDRESS\n"
"  %attrs;                              -- %coreattrs, %i18n, %events --\n"
"  >\n"
"\n"
"<!ELEMENT DIV - - (%flow;)*            -- generic language/style container -->\n"
"<!ATTLIST DIV\n"
"  %attrs;                              -- %coreattrs, %i18n, %events --\n"
"  %reserved;                           -- reserved for possible future use --\n"
"  >\n"
"\n"
"\n"
"<!--================== The Anchor Element ================================-->\n"
"\n"
"<!ENTITY % Shape \"(rect|circle|poly|default)\">\n"
"<!ENTITY % Coords \"CDATA\" -- comma-separated list of lengths -->\n"
"\n"
"<!ELEMENT A - - (%inline;)* -(A)       -- anchor -->\n"
"<!ATTLIST A\n"
"  %attrs;                              -- %coreattrs, %i18n, %events --\n"
"  charset     %Charset;      #IMPLIED  -- char encoding of linked resource --\n"
"  type        %ContentType;  #IMPLIED  -- advisory content type --\n"
"  name        CDATA          #IMPLIED  -- named link end --\n"
"  href        %URI;          #IMPLIED  -- URI for linked resource --\n"
"  hreflang    %LanguageCode; #IMPLIED  -- language code --\n"
"  rel         %LinkTypes;    #IMPLIED  -- forward link types --\n"
"  rev         %LinkTypes;    #IMPLIED  -- reverse link types --\n"
"  accesskey   %Character;    #IMPLIED  -- accessibility key character --\n"
"  shape       %Shape;        rect      -- for use with client-side image maps --\n"
"  coords      %Coords;       #IMPLIED  -- for use with client-side image maps --\n"
"  tabindex    NUMBER         #IMPLIED  -- position in tabbing order --\n"
"  onfocus     %Script;       #IMPLIED  -- the element got the focus --\n"
"  onblur      %Script;       #IMPLIED  -- the element lost the focus --\n"
"  >\n"
"\n"
"<!--================== Client-side image maps ============================-->\n"
"\n"
"<!-- These can be placed in the same document or grouped in a\n"
"     separate document although this isn't yet widely supported -->\n"
"\n"
"<!ELEMENT MAP - - ((%block;) | AREA)+ -- client-side image map -->\n"
"<!ATTLIST MAP\n"
"  %attrs;                              -- %coreattrs, %i18n, %events --\n"
"  name        CDATA          #REQUIRED -- for reference by usemap --\n"
"  >\n"
"\n"
"<!ELEMENT AREA - O EMPTY               -- client-side image map area -->\n"
"<!ATTLIST AREA\n"
"  %attrs;                              -- %coreattrs, %i18n, %events --\n"
"  shape       %Shape;        rect      -- controls interpretation of coords --\n"
"  coords      %Coords;       #IMPLIED  -- comma-separated list of lengths --\n"
"  href        %URI;          #IMPLIED  -- URI for linked resource --\n"
"  nohref      (nohref)       #IMPLIED  -- this region has no action --\n"
"  alt         %Text;         #REQUIRED -- short description --\n"
"  tabindex    NUMBER         #IMPLIED  -- position in tabbing order --\n"
"  accesskey   %Character;    #IMPLIED  -- accessibility key character --\n"
"  onfocus     %Script;       #IMPLIED  -- the element got the focus --\n"
"  onblur      %Script;       #IMPLIED  -- the element lost the focus --\n"
"  >\n"
"\n"
"<!--================== The LINK Element ==================================-->\n"
"\n"
"<!--\n"
"  Relationship values can be used in principle:\n"
"\n"
"   a) for document specific toolbars/menus when used\n"
"      with the LINK element in document head e.g.\n"
"        start, contents, previous, next, index, end, help\n"
"   b) to link to a separate style sheet (rel=stylesheet)\n"
"   c) to make a link to a script (rel=script)\n"
"   d) by stylesheets to control how collections of\n"
"      html nodes are rendered into printed documents\n"
"   e) to make a link to a printable version of this document\n"
"      e.g. a postscript or pdf version (rel=alternate media=print)\n"
"-->\n"
"\n"
"<!ELEMENT LINK - O EMPTY               -- a media-independent link -->\n"
"<!ATTLIST LINK\n"
"  %attrs;                              -- %coreattrs, %i18n, %events --\n"
"  charset     %Charset;      #IMPLIED  -- char encoding of linked resource --\n"
"  href        %URI;          #IMPLIED  -- URI for linked resource --\n"
"  hreflang    %LanguageCode; #IMPLIED  -- language code --\n"
"  type        %ContentType;  #IMPLIED  -- advisory content type --\n"
"  rel         %LinkTypes;    #IMPLIED  -- forward link types --\n"
"  rev         %LinkTypes;    #IMPLIED  -- reverse link types --\n"
"  media       %MediaDesc;    #IMPLIED  -- for rendering on these media --\n"
"  >\n"
"\n"
"<!--=================== Images ===========================================-->\n"
"\n"
"<!-- Length defined in strict DTD for cellpadding/cellspacing -->\n"
"<!ENTITY % Length \"CDATA\" -- nn for pixels or nn% for percentage length -->\n"
"<!ENTITY % MultiLength \"CDATA\" -- pixel, percentage, or relative -->\n"
"\n"
"<![ %HTML.Frameset; [\n"
"<!ENTITY % MultiLengths \"CDATA\" -- comma-separated list of MultiLength -->\n"
"]]>\n"
"\n"
"<!ENTITY % Pixels \"CDATA\" -- integer representing length in pixels -->\n"
"\n"
"\n"
"<!-- To avoid problems with text-only UAs as well as \n"
"   to make image content understandable and navigable \n"
"   to users of non-visual UAs, you need to provide\n"
"   a description with ALT, and avoid server-side image maps -->\n"
"<!ELEMENT IMG - O EMPTY                -- Embedded image -->\n"
"<!ATTLIST IMG\n"
"  %attrs;                              -- %coreattrs, %i18n, %events --\n"
"  src         %URI;          #REQUIRED -- URI of image to embed --\n"
"  alt         %Text;         #REQUIRED -- short description --\n"
"  longdesc    %URI;          #IMPLIED  -- link to long description\n"
"                                          (complements alt) --\n"
"  name        CDATA          #IMPLIED  -- name of image for scripting --\n"
"  height      %Length;       #IMPLIED  -- override height --\n"
"  width       %Length;       #IMPLIED  -- override width --\n"
"  usemap      %URI;          #IMPLIED  -- use client-side image map --\n"
"  ismap       (ismap)        #IMPLIED  -- use server-side image map --\n"
"  >\n"
"\n"
"<!-- USEMAP points to a MAP element which may be in this document\n"
"  or an external document, although the latter is not widely supported -->\n"
"\n"
"<!--==================== OBJECT ======================================-->\n"
"<!--\n"
"  OBJECT is used to embed objects as part of HTML pages \n"
"  PARAM elements should precede other content. SGML mixed content\n"
"  model technicality precludes specifying this formally ...\n"
"-->\n"
"\n"
"<!ELEMENT OBJECT - - (PARAM | %flow;)*\n"
" -- generic embedded object -->\n"
"<!ATTLIST OBJECT\n"
"  %attrs;                              -- %coreattrs, %i18n, %events --\n"
"  declare     (declare)      #IMPLIED  -- declare but don't instantiate flag --\n"
"  classid     %URI;          #IMPLIED  -- identifies an implementation --\n"
"  codebase    %URI;          #IMPLIED  -- base URI for classid, data, archive--\n"
"  data        %URI;          #IMPLIED  -- reference to object's data --\n"
"  type        %ContentType;  #IMPLIED  -- content type for data --\n"
"  codetype    %ContentType;  #IMPLIED  -- content type for code --\n"
"  archive     CDATA          #IMPLIED  -- space-separated list of URIs --\n"
"  standby     %Text;         #IMPLIED  -- message to show while loading --\n"
"  height      %Length;       #IMPLIED  -- override height --\n"
"  width       %Length;       #IMPLIED  -- override width --\n"
"  usemap      %URI;          #IMPLIED  -- use client-side image map --\n"
"  name        CDATA          #IMPLIED  -- submit as part of form --\n"
"  tabindex    NUMBER         #IMPLIED  -- position in tabbing order --\n"
"  %reserved;                           -- reserved for possible future use --\n"
"  >\n"
"\n"
"<!ELEMENT PARAM - O EMPTY              -- named property value -->\n"
"<!ATTLIST PARAM\n"
"  id          ID             #IMPLIED  -- document-wide unique id --\n"
"  name        CDATA          #REQUIRED -- property name --\n"
"  value       CDATA          #IMPLIED  -- property value --\n"
"  valuetype   (DATA|REF|OBJECT) DATA   -- How to interpret value --\n"
"  type        %ContentType;  #IMPLIED  -- content type for value\n"
"                                          when valuetype=ref --\n"
"  >\n"
"\n"
"\n"
"<!--=================== Horizontal Rule ==================================-->\n"
"\n"
"<!ELEMENT HR - O EMPTY -- horizontal rule -->\n"
"<!ATTLIST HR\n"
"  %attrs;                              -- %coreattrs, %i18n, %events --\n"
"  >\n"
"\n"
"<!--=================== Paragraphs =======================================-->\n"
"\n"
"<!ELEMENT P - O (%inline;)*            -- paragraph -->\n"
"<!ATTLIST P\n"
"  %attrs;                              -- %coreattrs, %i18n, %events --\n"
"  >\n"
"\n"
"<!--=================== Headings =========================================-->\n"
"\n"
"<!--\n"
"  There are six levels of headings from H1 (the most important)\n"
"  to H6 (the least important).\n"
"-->\n"
"\n"
"<!ELEMENT (%heading;)  - - (%inline;)* -- heading -->\n"
"<!ATTLIST (%heading;)\n"
"  %attrs;                              -- %coreattrs, %i18n, %events --\n"
"  >\n"
"\n"
"<!--=================== Preformatted Text ================================-->\n"
"\n"
"<!-- excludes markup for images and changes in font size -->\n"
"<!ENTITY % pre.exclusion \"IMG|OBJECT|BIG|SMALL|SUB|SUP\">\n"
"\n"
"<!ELEMENT PRE - - (%inline;)* -(%pre.exclusion;) -- preformatted text -->\n"
"<!ATTLIST PRE\n"
"  %attrs;                              -- %coreattrs, %i18n, %events --\n"
"  >\n"
"\n"
"<!--===================== Inline Quotes ==================================-->\n"
"\n"
"<!ELEMENT Q - - (%inline;)*            -- short inline quotation -->\n"
"<!ATTLIST Q\n"
"  %attrs;                              -- %coreattrs, %i18n, %events --\n"
"  cite        %URI;          #IMPLIED  -- URI for source document or msg --\n"
"  >\n"
"\n"
"<!--=================== Block-like Quotes ================================-->\n"
"\n"
"<!ELEMENT BLOCKQUOTE - - (%block;|SCRIPT)+ -- long quotation -->\n"
"<!ATTLIST BLOCKQUOTE\n"
"  %attrs;                              -- %coreattrs, %i18n, %events --\n"
"  cite        %URI;          #IMPLIED  -- URI for source document or msg --\n"
"  >\n"
"\n"
"<!--=================== Inserted/Deleted Text ============================-->\n"
"\n"
"\n"
"<!-- INS/DEL are handled by inclusion on BODY -->\n"
"<!ELEMENT (INS|DEL) - - (%flow;)*      -- inserted text, deleted text -->\n"
"<!ATTLIST (INS|DEL)\n"
"  %attrs;                              -- %coreattrs, %i18n, %events --\n"
"  cite        %URI;          #IMPLIED  -- info on reason for change --\n"
"  datetime    %Datetime;     #IMPLIED  -- date and time of change --\n"
"  >\n"
"\n"
"<!--=================== Lists ============================================-->\n"
"\n"
"<!-- definition lists - DT for term, DD for its definition -->\n"
"\n"
"<!ELEMENT DL - - (DT|DD)+              -- definition list -->\n"
"<!ATTLIST DL\n"
"  %attrs;                              -- %coreattrs, %i18n, %events --\n"
"  >\n"
"\n"
"<!ELEMENT DT - O (%inline;)*           -- definition term -->\n"
"<!ELEMENT DD - O (%flow;)*             -- definition description -->\n"
"<!ATTLIST (DT|DD)\n"
"  %attrs;                              -- %coreattrs, %i18n, %events --\n"
"  >\n"
"\n"
"\n"
"<!ELEMENT OL - - (LI)+                 -- ordered list -->\n"
"<!ATTLIST OL\n"
"  %attrs;                              -- %coreattrs, %i18n, %events --\n"
"  >\n"
"\n"
"<!-- Unordered Lists (UL) bullet styles -->\n"
"<!ELEMENT UL - - (LI)+                 -- unordered list -->\n"
"<!ATTLIST UL\n"
"  %attrs;                              -- %coreattrs, %i18n, %events --\n"
"  >\n"
"\n"
"\n"
"\n"
"<!ELEMENT LI - O (%flow;)*             -- list item -->\n"
"<!ATTLIST LI\n"
"  %attrs;                              -- %coreattrs, %i18n, %events --\n"
"  >\n"
"\n"
"<!--================ Forms ===============================================-->\n"
"<!ELEMENT FORM - - (%block;|SCRIPT)+ -(FORM) -- interactive form -->\n"
"<!ATTLIST FORM\n"
"  %attrs;                              -- %coreattrs, %i18n, %events --\n"
"  action      %URI;          #REQUIRED -- server-side form handler --\n"
"  method      (GET|POST)     GET       -- HTTP method used to submit the form--\n"
"  enctype     %ContentType;  \"application/x-www-form-urlencoded\"\n"
"  accept      %ContentTypes; #IMPLIED  -- list of MIME types for file upload --\n"
"  name        CDATA          #IMPLIED  -- name of form for scripting --\n"
"  onsubmit    %Script;       #IMPLIED  -- the form was submitted --\n"
"  onreset     %Script;       #IMPLIED  -- the form was reset --\n"
"  accept-charset %Charsets;  #IMPLIED  -- list of supported charsets --\n"
"  >\n"
"\n"
"<!-- Each label must not contain more than ONE field -->\n"
"<!ELEMENT LABEL - - (%inline;)* -(LABEL) -- form field label text -->\n"
"<!ATTLIST LABEL\n"
"  %attrs;                              -- %coreattrs, %i18n, %events --\n"
"  for         IDREF          #IMPLIED  -- matches field ID value --\n"
"  accesskey   %Character;    #IMPLIED  -- accessibility key character --\n"
"  onfocus     %Script;       #IMPLIED  -- the element got the focus --\n"
"  onblur      %Script;       #IMPLIED  -- the element lost the focus --\n"
"  >\n"
"\n"
"<!ENTITY % InputType\n"
"  \"(TEXT | PASSWORD | CHECKBOX |\n"
"    RADIO | SUBMIT | RESET |\n"
"    FILE | HIDDEN | IMAGE | BUTTON)\"\n"
"   >\n"
"\n"
"<!-- attribute name required for all but submit and reset -->\n"
"<!ELEMENT INPUT - O EMPTY              -- form control -->\n"
"<!ATTLIST INPUT\n"
"  %attrs;                              -- %coreattrs, %i18n, %events --\n"
"  type        %InputType;    TEXT      -- what kind of widget is needed --\n"
"  name        CDATA          #IMPLIED  -- submit as part of form --\n"
"  value       CDATA          #IMPLIED  -- Specify for radio buttons and checkboxes --\n"
"  checked     (checked)      #IMPLIED  -- for radio buttons and check boxes --\n"
"  disabled    (disabled)     #IMPLIED  -- unavailable in this context --\n"
"  readonly    (readonly)     #IMPLIED  -- for text and passwd --\n"
"  size        CDATA          #IMPLIED  -- specific to each type of field --\n"
"  maxlength   NUMBER         #IMPLIED  -- max chars for text fields --\n"
"  src         %URI;          #IMPLIED  -- for fields with images --\n"
"  alt         CDATA          #IMPLIED  -- short description --\n"
"  usemap      %URI;          #IMPLIED  -- use client-side image map --\n"
"  ismap       (ismap)        #IMPLIED  -- use server-side image map --\n"
"  tabindex    NUMBER         #IMPLIED  -- position in tabbing order --\n"
"  accesskey   %Character;    #IMPLIED  -- accessibility key character --\n"
"  onfocus     %Script;       #IMPLIED  -- the element got the focus --\n"
"  onblur      %Script;       #IMPLIED  -- the element lost the focus --\n"
"  onselect    %Script;       #IMPLIED  -- some text was selected --\n"
"  onchange    %Script;       #IMPLIED  -- the element value was changed --\n"
"  accept      %ContentTypes; #IMPLIED  -- list of MIME types for file upload --\n"
"  %reserved;                           -- reserved for possible future use --\n"
"  >\n"
"\n"
"<!ELEMENT SELECT - - (OPTGROUP|OPTION)+ -- option selector -->\n"
"<!ATTLIST SELECT\n"
"  %attrs;                              -- %coreattrs, %i18n, %events --\n"
"  name        CDATA          #IMPLIED  -- field name --\n"
"  size        NUMBER         #IMPLIED  -- rows visible --\n"
"  multiple    (multiple)     #IMPLIED  -- default is single selection --\n"
"  disabled    (disabled)     #IMPLIED  -- unavailable in this context --\n"
"  tabindex    NUMBER         #IMPLIED  -- position in tabbing order --\n"
"  onfocus     %Script;       #IMPLIED  -- the element got the focus --\n"
"  onblur      %Script;       #IMPLIED  -- the element lost the focus --\n"
"  onchange    %Script;       #IMPLIED  -- the element value was changed --\n"
"  %reserved;                           -- reserved for possible future use --\n"
"  >\n"
"\n"
"<!ELEMENT OPTGROUP - - (OPTION)+ -- option group -->\n"
"<!ATTLIST OPTGROUP\n"
"  %attrs;                              -- %coreattrs, %i18n, %events --\n"
"  disabled    (disabled)     #IMPLIED  -- unavailable in this context --\n"
"  label       %Text;         #REQUIRED -- for use in hierarchical menus --\n"
"  >\n"
"\n"
"<!ELEMENT OPTION - O (#PCDATA)         -- selectable choice -->\n"
"<!ATTLIST OPTION\n"
"  %attrs;                              -- %coreattrs, %i18n, %events --\n"
"  selected    (selected)     #IMPLIED\n"
"  disabled    (disabled)     #IMPLIED  -- unavailable in this context --\n"
"  label       %Text;         #IMPLIED  -- for use in hierarchical menus --\n"
"  value       CDATA          #IMPLIED  -- defaults to element content --\n"
"  >\n"
"\n"
"<!ELEMENT TEXTAREA - - (#PCDATA)       -- multi-line text field -->\n"
"<!ATTLIST TEXTAREA\n"
"  %attrs;                              -- %coreattrs, %i18n, %events --\n"
"  name        CDATA          #IMPLIED\n"
"  rows        NUMBER         #REQUIRED\n"
"  cols        NUMBER         #REQUIRED\n"
"  disabled    (disabled)     #IMPLIED  -- unavailable in this context --\n"
"  readonly    (readonly)     #IMPLIED\n"
"  tabindex    NUMBER         #IMPLIED  -- position in tabbing order --\n"
"  accesskey   %Character;    #IMPLIED  -- accessibility key character --\n"
"  onfocus     %Script;       #IMPLIED  -- the element got the focus --\n"
"  onblur      %Script;       #IMPLIED  -- the element lost the focus --\n"
"  onselect    %Script;       #IMPLIED  -- some text was selected --\n"
"  onchange    %Script;       #IMPLIED  -- the element value was changed --\n"
"  %reserved;                           -- reserved for possible future use --\n"
"  >\n"
"\n"
"<!--\n"
"  #PCDATA is to solve the mixed content problem,\n"
"  per specification only whitespace is allowed there!\n"
" -->\n"
"<!ELEMENT FIELDSET - - (#PCDATA,LEGEND,(%flow;)*) -- form control group -->\n"
"<!ATTLIST FIELDSET\n"
"  %attrs;                              -- %coreattrs, %i18n, %events --\n"
"  >\n"
"\n"
"<!ELEMENT LEGEND - - (%inline;)*       -- fieldset legend -->\n"
"\n"
"<!ATTLIST LEGEND\n"
"  %attrs;                              -- %coreattrs, %i18n, %events --\n"
"  accesskey   %Character;    #IMPLIED  -- accessibility key character --\n"
"  >\n"
"\n"
"<!ELEMENT BUTTON - -\n"
"     (%flow;)* -(A|%formctrl;|FORM|FIELDSET)\n"
"     -- push button -->\n"
"<!ATTLIST BUTTON\n"
"  %attrs;                              -- %coreattrs, %i18n, %events --\n"
"  name        CDATA          #IMPLIED\n"
"  value       CDATA          #IMPLIED  -- sent to server when submitted --\n"
"  type        (button|submit|reset) submit -- for use as form button --\n"
"  disabled    (disabled)     #IMPLIED  -- unavailable in this context --\n"
"  tabindex    NUMBER         #IMPLIED  -- position in tabbing order --\n"
"  accesskey   %Character;    #IMPLIED  -- accessibility key character --\n"
"  onfocus     %Script;       #IMPLIED  -- the element got the focus --\n"
"  onblur      %Script;       #IMPLIED  -- the element lost the focus --\n"
"  %reserved;                           -- reserved for possible future use --\n"
"  >\n"
"\n"
"<!--======================= Tables =======================================-->\n"
"\n"
"<!-- IETF HTML table standard, see [RFC1942] -->\n"
"\n"
"<!--\n"
" The BORDER attribute sets the thickness of the frame around the\n"
" table. The default units are screen pixels.\n"
"\n"
" The FRAME attribute specifies which parts of the frame around\n"
" the table should be rendered. The values are not the same as\n"
" CALS to avoid a name clash with the VALIGN attribute.\n"
"\n"
" The value \"border\" is included for backwards compatibility with\n"
" <TABLE BORDER> which yields frame=border and border=implied\n"
" For <TABLE BORDER=1> you get border=1 and frame=implied. In this\n"
" case, it is appropriate to treat this as frame=border for backwards\n"
" compatibility with deployed browsers.\n"
"-->\n"
"<!ENTITY % TFrame \"(void|above|below|hsides|lhs|rhs|vsides|box|border)\">\n"
"\n"
"<!--\n"
" The RULES attribute defines which rules to draw between cells:\n"
"\n"
" If RULES is absent then assume:\n"
"     \"none\" if BORDER is absent or BORDER=0 otherwise \"all\"\n"
"-->\n"
"\n"
"<!ENTITY % TRules \"(none | groups | rows | cols | all)\">\n"
"  \n"
"<!-- horizontal placement of table relative to document -->\n"
"<!ENTITY % TAlign \"(left|center|right)\">\n"
"\n"
"<!-- horizontal alignment attributes for cell contents -->\n"
"<!ENTITY % cellhalign\n"
"  \"align      (left|center|right|justify|char) #IMPLIED\n"
"   char       %Character;    #IMPLIED  -- alignment char, e.g. char=':' --\n"
"   charoff    %Length;       #IMPLIED  -- offset for alignment char --\"\n"
"  >\n"
"\n"
"<!-- vertical alignment attributes for cell contents -->\n"
"<!ENTITY % cellvalign\n"
"  \"valign     (top|middle|bottom|baseline) #IMPLIED\"\n"
"  >\n"
"\n"
"<!ELEMENT TABLE - -\n"
"     (CAPTION?, (COL*|COLGROUP*), THEAD?, TFOOT?, TBODY+)>\n"
"<!ELEMENT CAPTION  - - (%inline;)*     -- table caption -->\n"
"<!ELEMENT THEAD    - O (TR)+           -- table header -->\n"
"<!ELEMENT TFOOT    - O (TR)+           -- table footer -->\n"
"<!ELEMENT TBODY    O O (TR)+           -- table body -->\n"
"<!ELEMENT COLGROUP - O (COL)*          -- table column group -->\n"
"<!ELEMENT COL      - O EMPTY           -- table column -->\n"
"<!ELEMENT TR       - O (TH|TD)+        -- table row -->\n"
"<!ELEMENT (TH|TD)  - O (%flow;)*       -- table header cell, table data cell-->\n"
"\n"
"<!ATTLIST TABLE                        -- table element --\n"
"  %attrs;                              -- %coreattrs, %i18n, %events --\n"
"  summary     %Text;         #IMPLIED  -- purpose/structure for speech output--\n"
"  width       %Length;       #IMPLIED  -- table width --\n"
"  border      %Pixels;       #IMPLIED  -- controls frame width around table --\n"
"  frame       %TFrame;       #IMPLIED  -- which parts of frame to render --\n"
"  rules       %TRules;       #IMPLIED  -- rulings between rows and cols --\n"
"  cellspacing %Length;       #IMPLIED  -- spacing between cells --\n"
"  cellpadding %Length;       #IMPLIED  -- spacing within cells --\n"
"  %reserved;                           -- reserved for possible future use --\n"
"  datapagesize CDATA         #IMPLIED  -- reserved for possible future use --\n"
"  >\n"
"\n"
"\n"
"<!ATTLIST CAPTION\n"
"  %attrs;                              -- %coreattrs, %i18n, %events --\n"
"  >\n"
"\n"
"<!--\n"
"COLGROUP groups a set of COL elements. It allows you to group\n"
"several semantically related columns together.\n"
"-->\n"
"<!ATTLIST COLGROUP\n"
"  %attrs;                              -- %coreattrs, %i18n, %events --\n"
"  span        NUMBER         1         -- default number of columns in group --\n"
"  width       %MultiLength;  #IMPLIED  -- default width for enclosed COLs --\n"
"  %cellhalign;                         -- horizontal alignment in cells --\n"
"  %cellvalign;                         -- vertical alignment in cells --\n"
"  >\n"
"\n"
"<!--\n"
" COL elements define the alignment properties for cells in\n"
" one or more columns.\n"
"\n"
" The WIDTH attribute specifies the width of the columns, e.g.\n"
"\n"
"     width=64        width in screen pixels\n"
"     width=0.5*      relative width of 0.5\n"
"\n"
" The SPAN attribute causes the attributes of one\n"
" COL element to apply to more than one column.\n"
"-->\n"
"<!ATTLIST COL                          -- column groups and properties --\n"
"  %attrs;                              -- %coreattrs, %i18n, %events --\n"
"  span        NUMBER         1         -- COL attributes affect N columns --\n"
"  width       %MultiLength;  #IMPLIED  -- column width specification --\n"
"  %cellhalign;                         -- horizontal alignment in cells --\n"
"  %cellvalign;                         -- vertical alignment in cells --\n"
"  >\n"
"\n"
"<!--\n"
"    Use THEAD to duplicate headers when breaking table\n"
"    across page boundaries, or for static headers when\n"
"    TBODY sections are rendered in scrolling panel.\n"
"\n"
"    Use TFOOT to duplicate footers when breaking table\n"
"    across page boundaries, or for static footers when\n"
"    TBODY sections are rendered in scrolling panel.\n"
"\n"
"    Use multiple TBODY sections when rules are needed\n"
"    between groups of table rows.\n"
"-->\n"
"<!ATTLIST (THEAD|TBODY|TFOOT)          -- table section --\n"
"  %attrs;                              -- %coreattrs, %i18n, %events --\n"
"  %cellhalign;                         -- horizontal alignment in cells --\n"
"  %cellvalign;                         -- vertical alignment in cells --\n"
"  >\n"
"\n"
"<!ATTLIST TR                           -- table row --\n"
"  %attrs;                              -- %coreattrs, %i18n, %events --\n"
"  %cellhalign;                         -- horizontal alignment in cells --\n"
"  %cellvalign;                         -- vertical alignment in cells --\n"
"  >\n"
"\n"
"\n"
"\n"
"<!-- Scope is simpler than headers attribute for common tables -->\n"
"<!ENTITY % Scope \"(row|col|rowgroup|colgroup)\">\n"
"\n"
"<!-- TH is for headers, TD for data, but for cells acting as both use TD -->\n"
"<!ATTLIST (TH|TD)                      -- header or data cell --\n"
"  %attrs;                              -- %coreattrs, %i18n, %events --\n"
"  abbr        %Text;         #IMPLIED  -- abbreviation for header cell --\n"
"  axis        CDATA          #IMPLIED  -- comma-separated list of related headers--\n"
"  headers     IDREFS         #IMPLIED  -- list of id's for header cells --\n"
"  scope       %Scope;        #IMPLIED  -- scope covered by header cells --\n"
"  rowspan     NUMBER         1         -- number of rows spanned by cell --\n"
"  colspan     NUMBER         1         -- number of cols spanned by cell --\n"
"  %cellhalign;                         -- horizontal alignment in cells --\n"
"  %cellvalign;                         -- vertical alignment in cells --\n"
"  >\n"
"\n"
"\n"
"<!--================ Document Head =======================================-->\n"
"<!-- %head.misc; defined earlier on as \"SCRIPT|STYLE|META|LINK|OBJECT\" -->\n"
"<!ENTITY % head.content \"TITLE & BASE?\">\n"
"\n"
"<!ELEMENT HEAD O O (%head.content;) +(%head.misc;) -- document head -->\n"
"<!ATTLIST HEAD\n"
"  %i18n;                               -- lang, dir --\n"
"  profile     %URI;          #IMPLIED  -- named dictionary of meta info --\n"
"  >\n"
"\n"
"<!-- The TITLE element is not considered part of the flow of text.\n"
"       It should be displayed, for example as the page header or\n"
"       window title. Exactly one title is required per document.\n"
"    -->\n"
"<!ELEMENT TITLE - - (#PCDATA) -(%head.misc;) -- document title -->\n"
"<!ATTLIST TITLE %i18n>\n"
"\n"
"\n"
"<!ELEMENT BASE - O EMPTY               -- document base URI -->\n"
"<!ATTLIST BASE\n"
"  href        %URI;          #REQUIRED -- URI that acts as base URI --\n"
"  >\n"
"\n"
"<!ELEMENT META - O EMPTY               -- generic metainformation -->\n"
"<!ATTLIST META\n"
"  %i18n;                               -- lang, dir, for use with content --\n"
"  http-equiv  NAME           #IMPLIED  -- HTTP response header name  --\n"
"  name        NAME           #IMPLIED  -- metainformation name --\n"
"  content     CDATA          #REQUIRED -- associated information --\n"
"  scheme      CDATA          #IMPLIED  -- select form of content --\n"
"  >\n"
"\n"
"<!ELEMENT STYLE - - %StyleSheet        -- style info -->\n"
"<!ATTLIST STYLE\n"
"  %i18n;                               -- lang, dir, for use with title --\n"
"  type        %ContentType;  #REQUIRED -- content type of style language --\n"
"  media       %MediaDesc;    #IMPLIED  -- designed for use with these media --\n"
"  title       %Text;         #IMPLIED  -- advisory title --\n"
"  >\n"
"\n"
"<!ELEMENT SCRIPT - - %Script;          -- script statements -->\n"
"<!ATTLIST SCRIPT\n"
"  charset     %Charset;      #IMPLIED  -- char encoding of linked resource --\n"
"  type        %ContentType;  #REQUIRED -- content type of script language --\n"
"  src         %URI;          #IMPLIED  -- URI for an external script --\n"
"  defer       (defer)        #IMPLIED  -- UA may defer execution of script --\n"
"  event       CDATA          #IMPLIED  -- reserved for possible future use --\n"
"  for         %URI;          #IMPLIED  -- reserved for possible future use --\n"
"  >\n"
"\n"
"<!ELEMENT NOSCRIPT - - (%block;)+\n"
"  -- alternate content container for non script-based rendering -->\n"
"<!ATTLIST NOSCRIPT\n"
"  %attrs;                              -- %coreattrs, %i18n, %events --\n"
"  >\n"
"\n"
"<!--================ Document Structure ==================================-->\n"
"<!ENTITY % html.content \"HEAD, BODY\">\n"
"\n"
"<!ELEMENT HTML O O (%html.content;)    -- document root element -->\n"
"<!ATTLIST HTML\n"
"  %i18n;                               -- lang, dir --\n"
"  >\n";


const char *	moXMLParser::g_html_loose_dtd =
"<!--\n"
"    This is the HTML 4.01 Transitional DTD, which includes\n"
"    presentation attributes and elements that W3C expects to phase out\n"
"    as support for style sheets matures. Authors should use the Strict\n"
"    DTD when possible, but may use the Transitional DTD when support\n"
"    for presentation attribute and elements is required.\n"
"\n"
"    HTML 4 includes mechanisms for style sheets, scripting,\n"
"    embedding objects, improved support for right to left and mixed\n"
"    direction text, and enhancements to forms for improved\n"
"    accessibility for people with disabilities.\n"
"\n"
"          Draft: $Date: 1999/12/24 23:37:48 $\n"
"\n"
"          Authors:\n"
"              Dave Raggett <dsr@w3.org>\n"
"              Arnaud Le Hors <lehors@w3.org>\n"
"              Ian Jacobs <ij@w3.org>\n"
"\n"
"    Further information about HTML 4.01 is available at:\n"
"\n"
"        http://www.w3.org/TR/1999/REC-html401-19991224\n"
"\n"
"\n"
"    The HTML 4.01 specification includes additional\n"
"    syntactic constraints that cannot be expressed within\n"
"    the DTDs.\n"
"\n"
"-->\n"
"<!ENTITY % HTML.Version \"-//W3C//DTD HTML 4.01 Transitional//EN\"\n"
"  -- Typical usage:\n"
"\n"
"    <!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\"\n"
"            \"http://www.w3.org/TR/html4/loose.dtd\">\n"
"    <html>\n"
"    <head>\n"
"    ...\n"
"    </head>\n"
"    <body>\n"
"    ...\n"
"    </body>\n"
"    </html>\n"
"\n"
"    The URI used as a system identifier with the public identifier allows\n"
"    the user agent to download the DTD and entity sets as needed.\n"
"\n"
"    The FPI for the Strict HTML 4.01 DTD is:\n"
"\n"
"        \"-//W3C//DTD HTML 4.01//EN\"\n"
"\n"
"    This version of the strict DTD is:\n"
"\n"
"        http://www.w3.org/TR/1999/REC-html401-19991224/strict.dtd\n"
"\n"
"    Authors should use the Strict DTD unless they need the\n"
"    presentation control for user agents that don't (adequately)\n"
"    support style sheets.\n"
"\n"
"    If you are writing a document that includes frames, use \n"
"    the following FPI:\n"
"\n"
"        \"-//W3C//DTD HTML 4.01 Frameset//EN\"\n"
"\n"
"    This version of the frameset DTD is:\n"
"\n"
"        http://www.w3.org/TR/1999/REC-html401-19991224/frameset.dtd\n"
"\n"
"    Use the following (relative) URIs to refer to \n"
"    the DTDs and entity definitions of this specification:\n"
"\n"
"    \"strict.dtd\"\n"
"    \"loose.dtd\"\n"
"    \"frameset.dtd\"\n"
"    \"HTMLlat1.ent\"\n"
"    \"HTMLsymbol.ent\"\n"
"    \"HTMLspecial.ent\"\n"
"\n"
"-->\n"
"\n"
"<!--================== Imported Names ====================================-->\n"
"<!-- Feature Switch for frameset documents -->\n"
"<!ENTITY % HTML.Frameset \"IGNORE\">\n"
"\n"
"<!ENTITY % ContentType \"CDATA\"\n"
"    -- media type, as per [RFC2045]\n"
"    -->\n"
"\n"
"<!ENTITY % ContentTypes \"CDATA\"\n"
"    -- comma-separated list of media types, as per [RFC2045]\n"
"    -->\n"
"\n"
"<!ENTITY % Charset \"CDATA\"\n"
"    -- a character encoding, as per [RFC2045]\n"
"    -->\n"
"\n"
"<!ENTITY % Charsets \"CDATA\"\n"
"    -- a space-separated list of character encodings, as per [RFC2045]\n"
"    -->\n"
"\n"
"<!ENTITY % LanguageCode \"NAME\"\n"
"    -- a language code, as per [RFC1766]\n"
"    -->\n"
"\n"
"<!ENTITY % Character \"CDATA\"\n"
"    -- a single character from [ISO10646] \n"
"    -->\n"
"\n"
"<!ENTITY % LinkTypes \"CDATA\"\n"
"    -- space-separated list of link types\n"
"    -->\n"
"\n"
"<!ENTITY % MediaDesc \"CDATA\"\n"
"    -- single or comma-separated list of media descriptors\n"
"    -->\n"
"\n"
"<!ENTITY % URI \"CDATA\"\n"
"    -- a Uniform Resource Identifier,\n"
"       see [URI]\n"
"    -->\n"
"\n"
"<!ENTITY % Datetime \"CDATA\" -- date and time information. ISO date format -->\n"
"\n"
"\n"
"<!ENTITY % Script \"CDATA\" -- script expression -->\n"
"\n"
"<!ENTITY % StyleSheet \"CDATA\" -- style sheet data -->\n"
"\n"
"<!ENTITY % FrameTarget \"CDATA\" -- render in this frame -->\n"
"\n"
"\n"
"<!ENTITY % Text \"CDATA\">\n"
"\n"
"\n"
"<!-- Parameter Entities -->\n"
"\n"
"<!ENTITY % head.misc \"SCRIPT|STYLE|META|LINK|OBJECT\" -- repeatable head elements -->\n"
"\n"
"<!ENTITY % heading \"H1|H2|H3|H4|H5|H6\">\n"
"\n"
"<!ENTITY % list \"UL | OL |  DIR | MENU\">\n"
"\n"
"<!ENTITY % preformatted \"PRE\">\n"
"\n"
"<!ENTITY % Color \"CDATA\" -- a color using sRGB: #RRGGBB as Hex values -->\n"
"\n"
"<!-- There are also 16 widely known color names with their sRGB values:\n"
"\n"
"    Black  = #000000    Green  = #008000\n"
"    Silver = #C0C0C0    Lime   = #00FF00\n"
"    Gray   = #808080    Olive  = #808000\n"
"    White  = #FFFFFF    Yellow = #FFFF00\n"
"    Maroon = #800000    Navy   = #000080\n"
"    Red    = #FF0000    Blue   = #0000FF\n"
"    Purple = #800080    Teal   = #008080\n"
"    Fuchsia= #FF00FF    Aqua   = #00FFFF\n"
" -->\n"
"\n"
"<!ENTITY % bodycolors \"\n"
"  bgcolor     %Color;        #IMPLIED  -- document background color --\n"
"  text        %Color;        #IMPLIED  -- document text color --\n"
"  link        %Color;        #IMPLIED  -- color of links --\n"
"  vlink       %Color;        #IMPLIED  -- color of visited links --\n"
"  alink       %Color;        #IMPLIED  -- color of selected links --\n"
"  \">\n"
"\n"
"<!--================ Character mnemonic entities =========================-->\n"
"\n"
"<!ENTITY % HTMLlat1 PUBLIC\n"
"   \"-//W3C//ENTITIES Latin1//EN//HTML\"\n"
"   \"HTMLlat1.ent\">\n"
"%HTMLlat1;\n"
"\n"
"<!ENTITY % HTMLsymbol PUBLIC\n"
"   \"-//W3C//ENTITIES Symbols//EN//HTML\"\n"
"   \"HTMLsymbol.ent\">\n"
"%HTMLsymbol;\n"
"\n"
"<!ENTITY % HTMLspecial PUBLIC\n"
"   \"-//W3C//ENTITIES Special//EN//HTML\"\n"
"   \"HTMLspecial.ent\">\n"
"%HTMLspecial;\n"
"<!--=================== Generic Attributes ===============================-->\n"
"\n"
"<!ENTITY % coreattrs\n"
" \"id          ID             #IMPLIED  -- document-wide unique id --\n"
"  class       CDATA          #IMPLIED  -- space-separated list of classes --\n"
"  style       %StyleSheet;   #IMPLIED  -- associated style info --\n"
"  title       %Text;         #IMPLIED  -- advisory title --\"\n"
"  >\n"
"\n"
"<!ENTITY % i18n\n"
" \"lang        %LanguageCode; #IMPLIED  -- language code --\n"
"  dir         (ltr|rtl)      #IMPLIED  -- direction for weak/neutral text --\"\n"
"  >\n"
"\n"
"<!ENTITY % events\n"
" \"onclick     %Script;       #IMPLIED  -- a pointer button was clicked --\n"
"  ondblclick  %Script;       #IMPLIED  -- a pointer button was double clicked--\n"
"  onmousedown %Script;       #IMPLIED  -- a pointer button was pressed down --\n"
"  onmouseup   %Script;       #IMPLIED  -- a pointer button was released --\n"
"  onmouseover %Script;       #IMPLIED  -- a pointer was moved onto --\n"
"  onmousemove %Script;       #IMPLIED  -- a pointer was moved within --\n"
"  onmouseout  %Script;       #IMPLIED  -- a pointer was moved away --\n"
"  onkeypress  %Script;       #IMPLIED  -- a key was pressed and released --\n"
"  onkeydown   %Script;       #IMPLIED  -- a key was pressed down --\n"
"  onkeyup     %Script;       #IMPLIED  -- a key was released --\"\n"
"  >\n"
"\n"
"<!-- Reserved Feature Switch -->\n"
"<!ENTITY % HTML.Reserved \"IGNORE\">\n"
"\n"
"<!-- The following attributes are reserved for possible future use -->\n"
"<![ %HTML.Reserved; [\n"
"<!ENTITY % reserved\n"
" \"datasrc     %URI;          #IMPLIED  -- a single or tabular Data Source --\n"
"  datafld     CDATA          #IMPLIED  -- the property or column name --\n"
"  dataformatas (plaintext|html) plaintext -- text or html --\"\n"
"  >\n"
"]]>\n"
"\n"
"<!ENTITY % reserved \"\">\n"
"\n"
"<!ENTITY % attrs \"%coreattrs; %i18n; %events;\">\n"
"\n"
"<!ENTITY % align \"align (left|center|right|justify)  #IMPLIED\"\n"
"                   -- default is left for ltr paragraphs, right for rtl --\n"
"  >\n"
"\n"
"<!--=================== Text Markup ======================================-->\n"
"\n"
"<!ENTITY % fontstyle\n"
" \"TT | I | B | U | S | STRIKE | BIG | SMALL\">\n"
"\n"
"<!ENTITY % phrase \"EM | STRONG | DFN | CODE |\n"
"                   SAMP | KBD | VAR | CITE | ABBR | ACRONYM\" >\n"
"\n"
"<!ENTITY % special\n"
"   \"A | IMG | APPLET | OBJECT | FONT | BASEFONT | BR | SCRIPT |\n"
"    MAP | Q | SUB | SUP | SPAN | BDO | IFRAME\">\n"
"\n"
"<!ENTITY % formctrl \"INPUT | SELECT | TEXTAREA | LABEL | BUTTON\">\n"
"\n"
"<!-- %inline; covers inline or \"text-level\" elements -->\n"
"<!ENTITY % inline \"#PCDATA | %fontstyle; | %phrase; | %special; | %formctrl;\">\n"
"\n"
"<!ELEMENT (%fontstyle;|%phrase;) - - (%inline;)*>\n"
"<!ATTLIST (%fontstyle;|%phrase;)\n"
"  %attrs;                              -- %coreattrs, %i18n, %events --\n"
"  >\n"
"\n"
"<!ELEMENT (SUB|SUP) - - (%inline;)*    -- subscript, superscript -->\n"
"<!ATTLIST (SUB|SUP)\n"
"  %attrs;                              -- %coreattrs, %i18n, %events --\n"
"  >\n"
"\n"
"<!ELEMENT SPAN - - (%inline;)*         -- generic language/style container -->\n"
"<!ATTLIST SPAN\n"
"  %attrs;                              -- %coreattrs, %i18n, %events --\n"
"  %reserved;			       -- reserved for possible future use --\n"
"  >\n"
"\n"
"<!ELEMENT BDO - - (%inline;)*          -- I18N BiDi over-ride -->\n"
"<!ATTLIST BDO\n"
"  %coreattrs;                          -- id, class, style, title --\n"
"  lang        %LanguageCode; #IMPLIED  -- language code --\n"
"  dir         (ltr|rtl)      #REQUIRED -- directionality --\n"
"  >\n"
"\n"
"<!ELEMENT BASEFONT - O EMPTY           -- base font size -->\n"
"<!ATTLIST BASEFONT\n"
"  id          ID             #IMPLIED  -- document-wide unique id --\n"
"  size        CDATA          #REQUIRED -- base font size for FONT elements --\n"
"  color       %Color;        #IMPLIED  -- text color --\n"
"  face        CDATA          #IMPLIED  -- comma-separated list of font names --\n"
"  >\n"
"\n"
"<!ELEMENT FONT - - (%inline;)*         -- local change to font -->\n"
"<!ATTLIST FONT\n"
"  %coreattrs;                          -- id, class, style, title --\n"
"  %i18n;		               -- lang, dir --\n"
"  size        CDATA          #IMPLIED  -- [+|-]nn e.g. size=\"+1\", size=\"4\" --\n"
"  color       %Color;        #IMPLIED  -- text color --\n"
"  face        CDATA          #IMPLIED  -- comma-separated list of font names --\n"
"  >\n"
"\n"
"<!ELEMENT BR - O EMPTY                 -- forced line break -->\n"
"<!ATTLIST BR\n"
"  %coreattrs;                          -- id, class, style, title --\n"
"  clear       (left|all|right|none) none -- control of text flow --\n"
"  >\n"
"\n"
"<!--================== HTML content models ===============================-->\n"
"\n"
"<!--\n"
"    HTML has two basic content models:\n"
"\n"
"        %inline;     character level elements and text strings\n"
"        %block;      block-like elements e.g. paragraphs and lists\n"
"-->\n"
"\n"
"<!ENTITY % block\n"
"     \"P | %heading; | %list; | %preformatted; | DL | DIV | CENTER |\n"
"      NOSCRIPT | NOFRAMES | BLOCKQUOTE | FORM | ISINDEX | HR |\n"
"      TABLE | FIELDSET | ADDRESS\">\n"
"\n"
"<!ENTITY % flow \"%block; | %inline;\">\n"
"\n"
"<!--=================== Document Body ====================================-->\n"
"\n"
"<!ELEMENT BODY O O (%flow;)* +(INS|DEL) -- document body -->\n"
"<!ATTLIST BODY\n"
"  %attrs;                              -- %coreattrs, %i18n, %events --\n"
"  onload          %Script;   #IMPLIED  -- the document has been loaded --\n"
"  onunload        %Script;   #IMPLIED  -- the document has been removed --\n"
"  background      %URI;      #IMPLIED  -- texture tile for document\n"
"                                          background --\n"
"  %bodycolors;                         -- bgcolor, text, link, vlink, alink --\n"
"  >\n"
"\n"
"<!ELEMENT ADDRESS - - ((%inline;)|P)*  -- information on author -->\n"
"<!ATTLIST ADDRESS\n"
"  %attrs;                              -- %coreattrs, %i18n, %events --\n"
"  >\n"
"\n"
"<!ELEMENT DIV - - (%flow;)*            -- generic language/style container -->\n"
"<!ATTLIST DIV\n"
"  %attrs;                              -- %coreattrs, %i18n, %events --\n"
"  %align;                              -- align, text alignment --\n"
"  %reserved;                           -- reserved for possible future use --\n"
"  >\n"
"\n"
"<!ELEMENT CENTER - - (%flow;)*         -- shorthand for DIV align=center -->\n"
"<!ATTLIST CENTER\n"
"  %attrs;                              -- %coreattrs, %i18n, %events --\n"
"  >\n"
"\n"
"<!--================== The Anchor Element ================================-->\n"
"\n"
"<!ENTITY % Shape \"(rect|circle|poly|default)\">\n"
"<!ENTITY % Coords \"CDATA\" -- comma-separated list of lengths -->\n"
"\n"
"<!ELEMENT A - - (%inline;)* -(A)       -- anchor -->\n"
"<!ATTLIST A\n"
"  %attrs;                              -- %coreattrs, %i18n, %events --\n"
"  charset     %Charset;      #IMPLIED  -- char encoding of linked resource --\n"
"  type        %ContentType;  #IMPLIED  -- advisory content type --\n"
"  name        CDATA          #IMPLIED  -- named link end --\n"
"  href        %URI;          #IMPLIED  -- URI for linked resource --\n"
"  hreflang    %LanguageCode; #IMPLIED  -- language code --\n"
"  target      %FrameTarget;  #IMPLIED  -- render in this frame --\n"
"  rel         %LinkTypes;    #IMPLIED  -- forward link types --\n"
"  rev         %LinkTypes;    #IMPLIED  -- reverse link types --\n"
"  accesskey   %Character;    #IMPLIED  -- accessibility key character --\n"
"  shape       %Shape;        rect      -- for use with client-side image maps --\n"
"  coords      %Coords;       #IMPLIED  -- for use with client-side image maps --\n"
"  tabindex    NUMBER         #IMPLIED  -- position in tabbing order --\n"
"  onfocus     %Script;       #IMPLIED  -- the element got the focus --\n"
"  onblur      %Script;       #IMPLIED  -- the element lost the focus --\n"
"  >\n"
"\n"
"<!--================== Client-side image maps ============================-->\n"
"\n"
"<!-- These can be placed in the same document or grouped in a\n"
"     separate document although this isn't yet widely supported -->\n"
"\n"
"<!ELEMENT MAP - - ((%block;) | AREA)+ -- client-side image map -->\n"
"<!ATTLIST MAP\n"
"  %attrs;                              -- %coreattrs, %i18n, %events --\n"
"  name        CDATA          #REQUIRED -- for reference by usemap --\n"
"  >\n"
"\n"
"<!ELEMENT AREA - O EMPTY               -- client-side image map area -->\n"
"<!ATTLIST AREA\n"
"  %attrs;                              -- %coreattrs, %i18n, %events --\n"
"  shape       %Shape;        rect      -- controls interpretation of coords --\n"
"  coords      %Coords;       #IMPLIED  -- comma-separated list of lengths --\n"
"  href        %URI;          #IMPLIED  -- URI for linked resource --\n"
"  target      %FrameTarget;  #IMPLIED  -- render in this frame --\n"
"  nohref      (nohref)       #IMPLIED  -- this region has no action --\n"
"  alt         %Text;         #REQUIRED -- short description --\n"
"  tabindex    NUMBER         #IMPLIED  -- position in tabbing order --\n"
"  accesskey   %Character;    #IMPLIED  -- accessibility key character --\n"
"  onfocus     %Script;       #IMPLIED  -- the element got the focus --\n"
"  onblur      %Script;       #IMPLIED  -- the element lost the focus --\n"
"  >\n"
"\n"
"<!--================== The LINK Element ==================================-->\n"
"\n"
"<!--\n"
"  Relationship values can be used in principle:\n"
"\n"
"   a) for document specific toolbars/menus when used\n"
"      with the LINK element in document head e.g.\n"
"        start, contents, previous, next, index, end, help\n"
"   b) to link to a separate style sheet (rel=stylesheet)\n"
"   c) to make a link to a script (rel=script)\n"
"   d) by stylesheets to control how collections of\n"
"      html nodes are rendered into printed documents\n"
"   e) to make a link to a printable version of this document\n"
"      e.g. a postscript or pdf version (rel=alternate media=print)\n"
"-->\n"
"\n"
"<!ELEMENT LINK - O EMPTY               -- a media-independent link -->\n"
"<!ATTLIST LINK\n"
"  %attrs;                              -- %coreattrs, %i18n, %events --\n"
"  charset     %Charset;      #IMPLIED  -- char encoding of linked resource --\n"
"  href        %URI;          #IMPLIED  -- URI for linked resource --\n"
"  hreflang    %LanguageCode; #IMPLIED  -- language code --\n"
"  type        %ContentType;  #IMPLIED  -- advisory content type --\n"
"  rel         %LinkTypes;    #IMPLIED  -- forward link types --\n"
"  rev         %LinkTypes;    #IMPLIED  -- reverse link types --\n"
"  media       %MediaDesc;    #IMPLIED  -- for rendering on these media --\n"
"  target      %FrameTarget;  #IMPLIED  -- render in this frame --\n"
"  >\n"
"\n"
"<!--=================== Images ===========================================-->\n"
"\n"
"<!-- Length defined in strict DTD for cellpadding/cellspacing -->\n"
"<!ENTITY % Length \"CDATA\" -- nn for pixels or nn% for percentage length -->\n"
"<!ENTITY % MultiLength \"CDATA\" -- pixel, percentage, or relative -->\n"
"\n"
"<![ %HTML.Frameset; [\n"
"<!ENTITY % MultiLengths \"CDATA\" -- comma-separated list of MultiLength -->\n"
"]]>\n"
"\n"
"<!ENTITY % Pixels \"CDATA\" -- integer representing length in pixels -->\n"
"\n"
"<!ENTITY % IAlign \"(top|middle|bottom|left|right)\" -- center? -->\n"
"\n"
"<!-- To avoid problems with text-only UAs as well as \n"
"   to make image content understandable and navigable \n"
"   to users of non-visual UAs, you need to provide\n"
"   a description with ALT, and avoid server-side image maps -->\n"
"<!ELEMENT IMG - O EMPTY                -- Embedded image -->\n"
"<!ATTLIST IMG\n"
"  %attrs;                              -- %coreattrs, %i18n, %events --\n"
"  src         %URI;          #REQUIRED -- URI of image to embed --\n"
"  alt         %Text;         #REQUIRED -- short description --\n"
"  longdesc    %URI;          #IMPLIED  -- link to long description\n"
"                                          (complements alt) --\n"
"  name        CDATA          #IMPLIED  -- name of image for scripting --\n"
"  height      %Length;       #IMPLIED  -- override height --\n"
"  width       %Length;       #IMPLIED  -- override width --\n"
"  usemap      %URI;          #IMPLIED  -- use client-side image map --\n"
"  ismap       (ismap)        #IMPLIED  -- use server-side image map --\n"
"  align       %IAlign;       #IMPLIED  -- vertical or horizontal alignment --\n"
"  border      %Pixels;       #IMPLIED  -- link border width --\n"
"  hspace      %Pixels;       #IMPLIED  -- horizontal gutter --\n"
"  vspace      %Pixels;       #IMPLIED  -- vertical gutter --\n"
"  >\n"
"\n"
"<!-- USEMAP points to a MAP element which may be in this document\n"
"  or an external document, although the latter is not widely supported -->\n"
"\n"
"<!--==================== OBJECT ======================================-->\n"
"<!--\n"
"  OBJECT is used to embed objects as part of HTML pages \n"
"  PARAM elements should precede other content. SGML mixed content\n"
"  model technicality precludes specifying this formally ...\n"
"-->\n"
"\n"
"<!ELEMENT OBJECT - - (PARAM | %flow;)*\n"
" -- generic embedded object -->\n"
"<!ATTLIST OBJECT\n"
"  %attrs;                              -- %coreattrs, %i18n, %events --\n"
"  declare     (declare)      #IMPLIED  -- declare but don't instantiate flag --\n"
"  classid     %URI;          #IMPLIED  -- identifies an implementation --\n"
"  codebase    %URI;          #IMPLIED  -- base URI for classid, data, archive--\n"
"  data        %URI;          #IMPLIED  -- reference to object's data --\n"
"  type        %ContentType;  #IMPLIED  -- content type for data --\n"
"  codetype    %ContentType;  #IMPLIED  -- content type for code --\n"
"  archive     CDATA          #IMPLIED  -- space-separated list of URIs --\n"
"  standby     %Text;         #IMPLIED  -- message to show while loading --\n"
"  height      %Length;       #IMPLIED  -- override height --\n"
"  width       %Length;       #IMPLIED  -- override width --\n"
"  usemap      %URI;          #IMPLIED  -- use client-side image map --\n"
"  name        CDATA          #IMPLIED  -- submit as part of form --\n"
"  tabindex    NUMBER         #IMPLIED  -- position in tabbing order --\n"
"  align       %IAlign;       #IMPLIED  -- vertical or horizontal alignment --\n"
"  border      %Pixels;       #IMPLIED  -- link border width --\n"
"  hspace      %Pixels;       #IMPLIED  -- horizontal gutter --\n"
"  vspace      %Pixels;       #IMPLIED  -- vertical gutter --\n"
"  %reserved;                           -- reserved for possible future use --\n"
"  >\n"
"\n"
"<!ELEMENT PARAM - O EMPTY              -- named property value -->\n"
"<!ATTLIST PARAM\n"
"  id          ID             #IMPLIED  -- document-wide unique id --\n"
"  name        CDATA          #REQUIRED -- property name --\n"
"  value       CDATA          #IMPLIED  -- property value --\n"
"  valuetype   (DATA|REF|OBJECT) DATA   -- How to interpret value --\n"
"  type        %ContentType;  #IMPLIED  -- content type for value\n"
"                                          when valuetype=ref --\n"
"  >\n"
"\n"
"<!--=================== Java APPLET ==================================-->\n"
"<!--\n"
"  One of code or object attributes must be present.\n"
"  Place PARAM elements before other content.\n"
"-->\n"
"<!ELEMENT APPLET - - (PARAM | %flow;)* -- Java applet -->\n"
"<!ATTLIST APPLET\n"
"  %coreattrs;                          -- id, class, style, title --\n"
"  codebase    %URI;          #IMPLIED  -- optional base URI for applet --\n"
"  archive     CDATA          #IMPLIED  -- comma-separated archive list --\n"
"  code        CDATA          #IMPLIED  -- applet class file --\n"
"  object      CDATA          #IMPLIED  -- serialized applet file --\n"
"  alt         %Text;         #IMPLIED  -- short description --\n"
"  name        CDATA          #IMPLIED  -- allows applets to find each other --\n"
"  width       %Length;       #REQUIRED -- initial width --\n"
"  height      %Length;       #REQUIRED -- initial height --\n"
"  align       %IAlign;       #IMPLIED  -- vertical or horizontal alignment --\n"
"  hspace      %Pixels;       #IMPLIED  -- horizontal gutter --\n"
"  vspace      %Pixels;       #IMPLIED  -- vertical gutter --\n"
"  >\n"
"\n"
"<!--=================== Horizontal Rule ==================================-->\n"
"\n"
"<!ELEMENT HR - O EMPTY -- horizontal rule -->\n"
"<!ATTLIST HR\n"
"  %attrs;                              -- %coreattrs, %i18n, %events --\n"
"  align       (left|center|right) #IMPLIED\n"
"  noshade     (noshade)      #IMPLIED\n"
"  size        %Pixels;       #IMPLIED\n"
"  width       %Length;       #IMPLIED\n"
"  >\n"
"\n"
"<!--=================== Paragraphs =======================================-->\n"
"\n"
"<!ELEMENT P - O (%inline;)*            -- paragraph -->\n"
"<!ATTLIST P\n"
"  %attrs;                              -- %coreattrs, %i18n, %events --\n"
"  %align;                              -- align, text alignment --\n"
"  >\n"
"\n"
"<!--=================== Headings =========================================-->\n"
"\n"
"<!--\n"
"  There are six levels of headings from H1 (the most important)\n"
"  to H6 (the least important).\n"
"-->\n"
"\n"
"<!ELEMENT (%heading;)  - - (%inline;)* -- heading -->\n"
"<!ATTLIST (%heading;)\n"
"  %attrs;                              -- %coreattrs, %i18n, %events --\n"
"  %align;                              -- align, text alignment --\n"
"  >\n"
"\n"
"<!--=================== Preformatted Text ================================-->\n"
"\n"
"<!-- excludes markup for images and changes in font size -->\n"
"<!ENTITY % pre.exclusion \"IMG|OBJECT|APPLET|BIG|SMALL|SUB|SUP|FONT|BASEFONT\">\n"
"\n"
"<!ELEMENT PRE - - (%inline;)* -(%pre.exclusion;) -- preformatted text -->\n"
"<!ATTLIST PRE\n"
"  %attrs;                              -- %coreattrs, %i18n, %events --\n"
"  width       NUMBER         #IMPLIED\n"
"  >\n"
"\n"
"<!--===================== Inline Quotes ==================================-->\n"
"\n"
"<!ELEMENT Q - - (%inline;)*            -- short inline quotation -->\n"
"<!ATTLIST Q\n"
"  %attrs;                              -- %coreattrs, %i18n, %events --\n"
"  cite        %URI;          #IMPLIED  -- URI for source document or msg --\n"
"  >\n"
"\n"
"<!--=================== Block-like Quotes ================================-->\n"
"\n"
"<!ELEMENT BLOCKQUOTE - - (%flow;)*     -- long quotation -->\n"
"<!ATTLIST BLOCKQUOTE\n"
"  %attrs;                              -- %coreattrs, %i18n, %events --\n"
"  cite        %URI;          #IMPLIED  -- URI for source document or msg --\n"
"  >\n"
"\n"
"<!--=================== Inserted/Deleted Text ============================-->\n"
"\n"
"\n"
"<!-- INS/DEL are handled by inclusion on BODY -->\n"
"<!ELEMENT (INS|DEL) - - (%flow;)*      -- inserted text, deleted text -->\n"
"<!ATTLIST (INS|DEL)\n"
"  %attrs;                              -- %coreattrs, %i18n, %events --\n"
"  cite        %URI;          #IMPLIED  -- info on reason for change --\n"
"  datetime    %Datetime;     #IMPLIED  -- date and time of change --\n"
"  >\n"
"\n"
"<!--=================== Lists ============================================-->\n"
"\n"
"<!-- definition lists - DT for term, DD for its definition -->\n"
"\n"
"<!ELEMENT DL - - (DT|DD)+              -- definition list -->\n"
"<!ATTLIST DL\n"
"  %attrs;                              -- %coreattrs, %i18n, %events --\n"
"  compact     (compact)      #IMPLIED  -- reduced interitem spacing --\n"
"  >\n"
"\n"
"<!ELEMENT DT - O (%inline;)*           -- definition term -->\n"
"<!ELEMENT DD - O (%flow;)*             -- definition description -->\n"
"<!ATTLIST (DT|DD)\n"
"  %attrs;                              -- %coreattrs, %i18n, %events --\n"
"  >\n"
"\n"
"<!-- Ordered lists (OL) Numbering style\n"
"\n"
"    1   arablic numbers     1, 2, 3, ...\n"
"    a   lower alpha         a, b, c, ...\n"
"    A   upper alpha         A, B, C, ...\n"
"    i   lower roman         i, ii, iii, ...\n"
"    I   upper roman         I, II, III, ...\n"
"\n"
"    The style is applied to the sequence number which by default\n"
"    is reset to 1 for the first list item in an ordered list.\n"
"\n"
"    This can't be expressed directly in SGML due to case folding.\n"
"-->\n"
"\n"
"<!ENTITY % OLStyle \"CDATA\"      -- constrained to: \"(1|a|A|i|I)\" -->\n"
"\n"
"<!ELEMENT OL - - (LI)+                 -- ordered list -->\n"
"<!ATTLIST OL\n"
"  %attrs;                              -- %coreattrs, %i18n, %events --\n"
"  type        %OLStyle;      #IMPLIED  -- numbering style --\n"
"  compact     (compact)      #IMPLIED  -- reduced interitem spacing --\n"
"  start       NUMBER         #IMPLIED  -- starting sequence number --\n"
"  >\n"
"\n"
"<!-- Unordered Lists (UL) bullet styles -->\n"
"<!ENTITY % ULStyle \"(disc|square|circle)\">\n"
"\n"
"<!ELEMENT UL - - (LI)+                 -- unordered list -->\n"
"<!ATTLIST UL\n"
"  %attrs;                              -- %coreattrs, %i18n, %events --\n"
"  type        %ULStyle;      #IMPLIED  -- bullet style --\n"
"  compact     (compact)      #IMPLIED  -- reduced interitem spacing --\n"
"  >\n"
"\n"
"<!ELEMENT (DIR|MENU) - - (LI)+ -(%block;) -- directory list, menu list -->\n"
"<!ATTLIST DIR\n"
"  %attrs;                              -- %coreattrs, %i18n, %events --\n"
"  compact     (compact)      #IMPLIED -- reduced interitem spacing --\n"
"  >\n"
"<!ATTLIST MENU\n"
"  %attrs;                              -- %coreattrs, %i18n, %events --\n"
"  compact     (compact)      #IMPLIED -- reduced interitem spacing --\n"
"  >\n"
"\n"
"<!ENTITY % LIStyle \"CDATA\" -- constrained to: \"(%ULStyle;|%OLStyle;)\" -->\n"
"\n"
"<!ELEMENT LI - O (%flow;)*             -- list item -->\n"
"<!ATTLIST LI\n"
"  %attrs;                              -- %coreattrs, %i18n, %events --\n"
"  type        %LIStyle;      #IMPLIED  -- list item style --\n"
"  value       NUMBER         #IMPLIED  -- reset sequence number --\n"
"  >\n"
"\n"
"<!--================ Forms ===============================================-->\n"
"<!ELEMENT FORM - - (%flow;)* -(FORM)   -- interactive form -->\n"
"<!ATTLIST FORM\n"
"  %attrs;                              -- %coreattrs, %i18n, %events --\n"
"  action      %URI;          #REQUIRED -- server-side form handler --\n"
"  method      (GET|POST)     GET       -- HTTP method used to submit the form--\n"
"  enctype     %ContentType;  \"application/x-www-form-urlencoded\"\n"
"  accept      %ContentTypes; #IMPLIED  -- list of MIME types for file upload --\n"
"  name        CDATA          #IMPLIED  -- name of form for scripting --\n"
"  onsubmit    %Script;       #IMPLIED  -- the form was submitted --\n"
"  onreset     %Script;       #IMPLIED  -- the form was reset --\n"
"  target      %FrameTarget;  #IMPLIED  -- render in this frame --\n"
"  accept-charset %Charsets;  #IMPLIED  -- list of supported charsets --\n"
"  >\n"
"\n"
"<!-- Each label must not contain more than ONE field -->\n"
"<!ELEMENT LABEL - - (%inline;)* -(LABEL) -- form field label text -->\n"
"<!ATTLIST LABEL\n"
"  %attrs;                              -- %coreattrs, %i18n, %events --\n"
"  for         IDREF          #IMPLIED  -- matches field ID value --\n"
"  accesskey   %Character;    #IMPLIED  -- accessibility key character --\n"
"  onfocus     %Script;       #IMPLIED  -- the element got the focus --\n"
"  onblur      %Script;       #IMPLIED  -- the element lost the focus --\n"
"  >\n"
"\n"
"<!ENTITY % InputType\n"
"  \"(TEXT | PASSWORD | CHECKBOX |\n"
"    RADIO | SUBMIT | RESET |\n"
"    FILE | HIDDEN | IMAGE | BUTTON)\"\n"
"   >\n"
"\n"
"<!-- attribute name required for all but submit and reset -->\n"
"<!ELEMENT INPUT - O EMPTY              -- form control -->\n"
"<!ATTLIST INPUT\n"
"  %attrs;                              -- %coreattrs, %i18n, %events --\n"
"  type        %InputType;    TEXT      -- what kind of widget is needed --\n"
"  name        CDATA          #IMPLIED  -- submit as part of form --\n"
"  value       CDATA          #IMPLIED  -- Specify for radio buttons and checkboxes --\n"
"  checked     (checked)      #IMPLIED  -- for radio buttons and check boxes --\n"
"  disabled    (disabled)     #IMPLIED  -- unavailable in this context --\n"
"  readonly    (readonly)     #IMPLIED  -- for text and passwd --\n"
"  size        CDATA          #IMPLIED  -- specific to each type of field --\n"
"  maxlength   NUMBER         #IMPLIED  -- max chars for text fields --\n"
"  src         %URI;          #IMPLIED  -- for fields with images --\n"
"  alt         CDATA          #IMPLIED  -- short description --\n"
"  usemap      %URI;          #IMPLIED  -- use client-side image map --\n"
"  ismap       (ismap)        #IMPLIED  -- use server-side image map --\n"
"  tabindex    NUMBER         #IMPLIED  -- position in tabbing order --\n"
"  accesskey   %Character;    #IMPLIED  -- accessibility key character --\n"
"  onfocus     %Script;       #IMPLIED  -- the element got the focus --\n"
"  onblur      %Script;       #IMPLIED  -- the element lost the focus --\n"
"  onselect    %Script;       #IMPLIED  -- some text was selected --\n"
"  onchange    %Script;       #IMPLIED  -- the element value was changed --\n"
"  accept      %ContentTypes; #IMPLIED  -- list of MIME types for file upload --\n"
"  align       %IAlign;       #IMPLIED  -- vertical or horizontal alignment --\n"
"  %reserved;                           -- reserved for possible future use --\n"
"  >\n"
"\n"
"<!ELEMENT SELECT - - (OPTGROUP|OPTION)+ -- option selector -->\n"
"<!ATTLIST SELECT\n"
"  %attrs;                              -- %coreattrs, %i18n, %events --\n"
"  name        CDATA          #IMPLIED  -- field name --\n"
"  size        NUMBER         #IMPLIED  -- rows visible --\n"
"  multiple    (multiple)     #IMPLIED  -- default is single selection --\n"
"  disabled    (disabled)     #IMPLIED  -- unavailable in this context --\n"
"  tabindex    NUMBER         #IMPLIED  -- position in tabbing order --\n"
"  onfocus     %Script;       #IMPLIED  -- the element got the focus --\n"
"  onblur      %Script;       #IMPLIED  -- the element lost the focus --\n"
"  onchange    %Script;       #IMPLIED  -- the element value was changed --\n"
"  %reserved;                           -- reserved for possible future use --\n"
"  >\n"
"\n"
"<!ELEMENT OPTGROUP - - (OPTION)+ -- option group -->\n"
"<!ATTLIST OPTGROUP\n"
"  %attrs;                              -- %coreattrs, %i18n, %events --\n"
"  disabled    (disabled)     #IMPLIED  -- unavailable in this context --\n"
"  label       %Text;         #REQUIRED -- for use in hierarchical menus --\n"
"  >\n"
"\n"
"<!ELEMENT OPTION - O (#PCDATA)         -- selectable choice -->\n"
"<!ATTLIST OPTION\n"
"  %attrs;                              -- %coreattrs, %i18n, %events --\n"
"  selected    (selected)     #IMPLIED\n"
"  disabled    (disabled)     #IMPLIED  -- unavailable in this context --\n"
"  label       %Text;         #IMPLIED  -- for use in hierarchical menus --\n"
"  value       CDATA          #IMPLIED  -- defaults to element content --\n"
"  >\n"
"\n"
"<!ELEMENT TEXTAREA - - (#PCDATA)       -- multi-line text field -->\n"
"<!ATTLIST TEXTAREA\n"
"  %attrs;                              -- %coreattrs, %i18n, %events --\n"
"  name        CDATA          #IMPLIED\n"
"  rows        NUMBER         #REQUIRED\n"
"  cols        NUMBER         #REQUIRED\n"
"  disabled    (disabled)     #IMPLIED  -- unavailable in this context --\n"
"  readonly    (readonly)     #IMPLIED\n"
"  tabindex    NUMBER         #IMPLIED  -- position in tabbing order --\n"
"  accesskey   %Character;    #IMPLIED  -- accessibility key character --\n"
"  onfocus     %Script;       #IMPLIED  -- the element got the focus --\n"
"  onblur      %Script;       #IMPLIED  -- the element lost the focus --\n"
"  onselect    %Script;       #IMPLIED  -- some text was selected --\n"
"  onchange    %Script;       #IMPLIED  -- the element value was changed --\n"
"  %reserved;                           -- reserved for possible future use --\n"
"  >\n"
"\n"
"<!--\n"
"  #PCDATA is to solve the mixed content problem,\n"
"  per specification only whitespace is allowed there!\n"
" -->\n"
"<!ELEMENT FIELDSET - - (#PCDATA,LEGEND,(%flow;)*) -- form control group -->\n"
"<!ATTLIST FIELDSET\n"
"  %attrs;                              -- %coreattrs, %i18n, %events --\n"
"  >\n"
"\n"
"<!ELEMENT LEGEND - - (%inline;)*       -- fieldset legend -->\n"
"<!ENTITY % LAlign \"(top|bottom|left|right)\">\n"
"\n"
"<!ATTLIST LEGEND\n"
"  %attrs;                              -- %coreattrs, %i18n, %events --\n"
"  accesskey   %Character;    #IMPLIED  -- accessibility key character --\n"
"  align       %LAlign;       #IMPLIED  -- relative to fieldset --\n"
"  >\n"
"\n"
"<!ELEMENT BUTTON - -\n"
"     (%flow;)* -(A|%formctrl;|FORM|ISINDEX|FIELDSET|IFRAME)\n"
"     -- push button -->\n"
"<!ATTLIST BUTTON\n"
"  %attrs;                              -- %coreattrs, %i18n, %events --\n"
"  name        CDATA          #IMPLIED\n"
"  value       CDATA          #IMPLIED  -- sent to server when submitted --\n"
"  type        (button|submit|reset) submit -- for use as form button --\n"
"  disabled    (disabled)     #IMPLIED  -- unavailable in this context --\n"
"  tabindex    NUMBER         #IMPLIED  -- position in tabbing order --\n"
"  accesskey   %Character;    #IMPLIED  -- accessibility key character --\n"
"  onfocus     %Script;       #IMPLIED  -- the element got the focus --\n"
"  onblur      %Script;       #IMPLIED  -- the element lost the focus --\n"
"  %reserved;                           -- reserved for possible future use --\n"
"  >\n"
"\n"
"<!--======================= Tables =======================================-->\n"
"\n"
"<!-- IETF HTML table standard, see [RFC1942] -->\n"
"\n"
"<!--\n"
" The BORDER attribute sets the thickness of the frame around the\n"
" table. The default units are screen pixels.\n"
"\n"
" The FRAME attribute specifies which parts of the frame around\n"
" the table should be rendered. The values are not the same as\n"
" CALS to avoid a name clash with the VALIGN attribute.\n"
"\n"
" The value \"border\" is included for backwards compatibility with\n"
" <TABLE BORDER> which yields frame=border and border=implied\n"
" For <TABLE BORDER=1> you get border=1 and frame=implied. In this\n"
" case, it is appropriate to treat this as frame=border for backwards\n"
" compatibility with deployed browsers.\n"
"-->\n"
"<!ENTITY % TFrame \"(void|above|below|hsides|lhs|rhs|vsides|box|border)\">\n"
"\n"
"<!--\n"
" The RULES attribute defines which rules to draw between cells:\n"
"\n"
" If RULES is absent then assume:\n"
"     \"none\" if BORDER is absent or BORDER=0 otherwise \"all\"\n"
"-->\n"
"\n"
"<!ENTITY % TRules \"(none | groups | rows | cols | all)\">\n"
"  \n"
"<!-- horizontal placement of table relative to document -->\n"
"<!ENTITY % TAlign \"(left|center|right)\">\n"
"\n"
"<!-- horizontal alignment attributes for cell contents -->\n"
"<!ENTITY % cellhalign\n"
"  \"align      (left|center|right|justify|char) #IMPLIED\n"
"   char       %Character;    #IMPLIED  -- alignment char, e.g. char=':' --\n"
"   charoff    %Length;       #IMPLIED  -- offset for alignment char --\"\n"
"  >\n"
"\n"
"<!-- vertical alignment attributes for cell contents -->\n"
"<!ENTITY % cellvalign\n"
"  \"valign     (top|middle|bottom|baseline) #IMPLIED\"\n"
"  >\n"
"\n"
"<!ELEMENT TABLE - -\n"
"     (CAPTION?, (COL*|COLGROUP*), THEAD?, TFOOT?, TBODY+)>\n"
"<!ELEMENT CAPTION  - - (%inline;)*     -- table caption -->\n"
"<!ELEMENT THEAD    - O (TR)+           -- table header -->\n"
"<!ELEMENT TFOOT    - O (TR)+           -- table footer -->\n"
"<!ELEMENT TBODY    O O (TR)+           -- table body -->\n"
"<!ELEMENT COLGROUP - O (COL)*          -- table column group -->\n"
"<!ELEMENT COL      - O EMPTY           -- table column -->\n"
"<!ELEMENT TR       - O (TH|TD)+        -- table row -->\n"
"<!ELEMENT (TH|TD)  - O (%flow;)*       -- table header cell, table data cell-->\n"
"\n"
"<!ATTLIST TABLE                        -- table element --\n"
"  %attrs;                              -- %coreattrs, %i18n, %events --\n"
"  summary     %Text;         #IMPLIED  -- purpose/structure for speech output--\n"
"  width       %Length;       #IMPLIED  -- table width --\n"
"  border      %Pixels;       #IMPLIED  -- controls frame width around table --\n"
"  frame       %TFrame;       #IMPLIED  -- which parts of frame to render --\n"
"  rules       %TRules;       #IMPLIED  -- rulings between rows and cols --\n"
"  cellspacing %Length;       #IMPLIED  -- spacing between cells --\n"
"  cellpadding %Length;       #IMPLIED  -- spacing within cells --\n"
"  align       %TAlign;       #IMPLIED  -- table position relative to window --\n"
"  bgcolor     %Color;        #IMPLIED  -- background color for cells --\n"
"  %reserved;                           -- reserved for possible future use --\n"
"  datapagesize CDATA         #IMPLIED  -- reserved for possible future use --\n"
"  >\n"
"\n"
"<!ENTITY % CAlign \"(top|bottom|left|right)\">\n"
"\n"
"<!ATTLIST CAPTION\n"
"  %attrs;                              -- %coreattrs, %i18n, %events --\n"
"  align       %CAlign;       #IMPLIED  -- relative to table --\n"
"  >\n"
"\n"
"<!--\n"
"COLGROUP groups a set of COL elements. It allows you to group\n"
"several semantically related columns together.\n"
"-->\n"
"<!ATTLIST COLGROUP\n"
"  %attrs;                              -- %coreattrs, %i18n, %events --\n"
"  span        NUMBER         1         -- default number of columns in group --\n"
"  width       %MultiLength;  #IMPLIED  -- default width for enclosed COLs --\n"
"  %cellhalign;                         -- horizontal alignment in cells --\n"
"  %cellvalign;                         -- vertical alignment in cells --\n"
"  >\n"
"\n"
"<!--\n"
" COL elements define the alignment properties for cells in\n"
" one or more columns.\n"
"\n"
" The WIDTH attribute specifies the width of the columns, e.g.\n"
"\n"
"     width=64        width in screen pixels\n"
"     width=0.5*      relative width of 0.5\n"
"\n"
" The SPAN attribute causes the attributes of one\n"
" COL element to apply to more than one column.\n"
"-->\n"
"<!ATTLIST COL                          -- column groups and properties --\n"
"  %attrs;                              -- %coreattrs, %i18n, %events --\n"
"  span        NUMBER         1         -- COL attributes affect N columns --\n"
"  width       %MultiLength;  #IMPLIED  -- column width specification --\n"
"  %cellhalign;                         -- horizontal alignment in cells --\n"
"  %cellvalign;                         -- vertical alignment in cells --\n"
"  >\n"
"\n"
"<!--\n"
"    Use THEAD to duplicate headers when breaking table\n"
"    across page boundaries, or for static headers when\n"
"    TBODY sections are rendered in scrolling panel.\n"
"\n"
"    Use TFOOT to duplicate footers when breaking table\n"
"    across page boundaries, or for static footers when\n"
"    TBODY sections are rendered in scrolling panel.\n"
"\n"
"    Use multiple TBODY sections when rules are needed\n"
"    between groups of table rows.\n"
"-->\n"
"<!ATTLIST (THEAD|TBODY|TFOOT)          -- table section --\n"
"  %attrs;                              -- %coreattrs, %i18n, %events --\n"
"  %cellhalign;                         -- horizontal alignment in cells --\n"
"  %cellvalign;                         -- vertical alignment in cells --\n"
"  >\n"
"\n"
"<!ATTLIST TR                           -- table row --\n"
"  %attrs;                              -- %coreattrs, %i18n, %events --\n"
"  %cellhalign;                         -- horizontal alignment in cells --\n"
"  %cellvalign;                         -- vertical alignment in cells --\n"
"  bgcolor     %Color;        #IMPLIED  -- background color for row --\n"
"  >\n"
"\n"
"\n"
"<!-- Scope is simpler than headers attribute for common tables -->\n"
"<!ENTITY % Scope \"(row|col|rowgroup|colgroup)\">\n"
"\n"
"<!-- TH is for headers, TD for data, but for cells acting as both use TD -->\n"
"<!ATTLIST (TH|TD)                      -- header or data cell --\n"
"  %attrs;                              -- %coreattrs, %i18n, %events --\n"
"  abbr        %Text;         #IMPLIED  -- abbreviation for header cell --\n"
"  axis        CDATA          #IMPLIED  -- comma-separated list of related headers--\n"
"  headers     IDREFS         #IMPLIED  -- list of id's for header cells --\n"
"  scope       %Scope;        #IMPLIED  -- scope covered by header cells --\n"
"  rowspan     NUMBER         1         -- number of rows spanned by cell --\n"
"  colspan     NUMBER         1         -- number of cols spanned by cell --\n"
"  %cellhalign;                         -- horizontal alignment in cells --\n"
"  %cellvalign;                         -- vertical alignment in cells --\n"
"  nowrap      (nowrap)       #IMPLIED  -- suppress word wrap --\n"
"  bgcolor     %Color;        #IMPLIED  -- cell background color --\n"
"  width       %Length;       #IMPLIED  -- width for cell --\n"
"  height      %Length;       #IMPLIED  -- height for cell --\n"
"  >\n"
"\n"
"<!--================== Document Frames ===================================-->\n"
"\n"
"<!--\n"
"  The content model for HTML documents depends on whether the HEAD is\n"
"  followed by a FRAMESET or BODY element. The widespread omission of\n"
"  the BODY start tag makes it impractical to define the content model\n"
"  without the use of a marked section.\n"
"-->\n"
"\n"
"<![ %HTML.Frameset; [\n"
"<!ELEMENT FRAMESET - - ((FRAMESET|FRAME)+ & NOFRAMES?) -- window subdivision-->\n"
"<!ATTLIST FRAMESET\n"
"  %coreattrs;                          -- id, class, style, title --\n"
"  rows        %MultiLengths; #IMPLIED  -- list of lengths,\n"
"                                          default: 100% (1 row) --\n"
"  cols        %MultiLengths; #IMPLIED  -- list of lengths,\n"
"                                          default: 100% (1 col) --\n"
"  onload      %Script;       #IMPLIED  -- all the frames have been loaded  -- \n"
"  onunload    %Script;       #IMPLIED  -- all the frames have been removed -- \n"
"  >\n"
"]]>\n"
"\n"
"<![ %HTML.Frameset; [\n"
"<!-- reserved frame names start with \"_\" otherwise starts with letter -->\n"
"<!ELEMENT FRAME - O EMPTY              -- subwindow -->\n"
"<!ATTLIST FRAME\n"
"  %coreattrs;                          -- id, class, style, title --\n"
"  longdesc    %URI;          #IMPLIED  -- link to long description\n"
"                                          (complements title) --\n"
"  name        CDATA          #IMPLIED  -- name of frame for targetting --\n"
"  src         %URI;          #IMPLIED  -- source of frame content --\n"
"  frameborder (1|0)          1         -- request frame borders? --\n"
"  marginwidth %Pixels;       #IMPLIED  -- margin widths in pixels --\n"
"  marginheight %Pixels;      #IMPLIED  -- margin height in pixels --\n"
"  noresize    (noresize)     #IMPLIED  -- allow users to resize frames? --\n"
"  scrolling   (yes|no|auto)  auto      -- scrollbar or none --\n"
"  >\n"
"]]>\n"
"\n"
"<!ELEMENT IFRAME - - (%flow;)*         -- inline subwindow -->\n"
"<!ATTLIST IFRAME\n"
"  %coreattrs;                          -- id, class, style, title --\n"
"  longdesc    %URI;          #IMPLIED  -- link to long description\n"
"                                          (complements title) --\n"
"  name        CDATA          #IMPLIED  -- name of frame for targetting --\n"
"  src         %URI;          #IMPLIED  -- source of frame content --\n"
"  frameborder (1|0)          1         -- request frame borders? --\n"
"  marginwidth %Pixels;       #IMPLIED  -- margin widths in pixels --\n"
"  marginheight %Pixels;      #IMPLIED  -- margin height in pixels --\n"
"  scrolling   (yes|no|auto)  auto      -- scrollbar or none --\n"
"  align       %IAlign;       #IMPLIED  -- vertical or horizontal alignment --\n"
"  height      %Length;       #IMPLIED  -- frame height --\n"
"  width       %Length;       #IMPLIED  -- frame width --\n"
"  >\n"
"\n"
"<![ %HTML.Frameset; [\n"
"<!ENTITY % noframes.content \"(BODY) -(NOFRAMES)\">\n"
"]]>\n"
"\n"
"<!ENTITY % noframes.content \"(%flow;)*\">\n"
"\n"
"<!ELEMENT NOFRAMES - - %noframes.content;\n"
" -- alternate content container for non frame-based rendering -->\n"
"<!ATTLIST NOFRAMES\n"
"  %attrs;                              -- %coreattrs, %i18n, %events --\n"
"  >\n"
"\n"
"<!--================ Document Head =======================================-->\n"
"<!-- %head.misc; defined earlier on as \"SCRIPT|STYLE|META|LINK|OBJECT\" -->\n"
"<!ENTITY % head.content \"TITLE & ISINDEX? & BASE?\">\n"
"\n"
"<!ELEMENT HEAD O O (%head.content;) +(%head.misc;) -- document head -->\n"
"<!ATTLIST HEAD\n"
"  %i18n;                               -- lang, dir --\n"
"  profile     %URI;          #IMPLIED  -- named dictionary of meta info --\n"
"  >\n"
"\n"
"<!-- The TITLE element is not considered part of the flow of text.\n"
"       It should be displayed, for example as the page header or\n"
"       window title. Exactly one title is required per document.\n"
"    -->\n"
"<!ELEMENT TITLE - - (#PCDATA) -(%head.misc;) -- document title -->\n"
"<!ATTLIST TITLE %i18n>\n"
"\n"
"<!ELEMENT ISINDEX - O EMPTY            -- single line prompt -->\n"
"<!ATTLIST ISINDEX\n"
"  %coreattrs;                          -- id, class, style, title --\n"
"  %i18n;                               -- lang, dir --\n"
"  prompt      %Text;         #IMPLIED  -- prompt message -->\n"
"\n"
"<!ELEMENT BASE - O EMPTY               -- document base URI -->\n"
"<!ATTLIST BASE\n"
"  href        %URI;          #IMPLIED  -- URI that acts as base URI --\n"
"  target      %FrameTarget;  #IMPLIED  -- render in this frame --\n"
"  >\n"
"\n"
"<!ELEMENT META - O EMPTY               -- generic metainformation -->\n"
"<!ATTLIST META\n"
"  %i18n;                               -- lang, dir, for use with content --\n"
"  http-equiv  NAME           #IMPLIED  -- HTTP response header name  --\n"
"  name        NAME           #IMPLIED  -- metainformation name --\n"
"  content     CDATA          #REQUIRED -- associated information --\n"
"  scheme      CDATA          #IMPLIED  -- select form of content --\n"
"  >\n"
"\n"
"<!ELEMENT STYLE - - %StyleSheet        -- style info -->\n"
"<!ATTLIST STYLE\n"
"  %i18n;                               -- lang, dir, for use with title --\n"
"  type        %ContentType;  #REQUIRED -- content type of style language --\n"
"  media       %MediaDesc;    #IMPLIED  -- designed for use with these media --\n"
"  title       %Text;         #IMPLIED  -- advisory title --\n"
"  >\n"
"\n"
"<!ELEMENT SCRIPT - - %Script;          -- script statements -->\n"
"<!ATTLIST SCRIPT\n"
"  charset     %Charset;      #IMPLIED  -- char encoding of linked resource --\n"
"  type        %ContentType;  #REQUIRED -- content type of script language --\n"
"  language    CDATA          #IMPLIED  -- predefined script language name --\n"
"  src         %URI;          #IMPLIED  -- URI for an external script --\n"
"  defer       (defer)        #IMPLIED  -- UA may defer execution of script --\n"
"  event       CDATA          #IMPLIED  -- reserved for possible future use --\n"
"  for         %URI;          #IMPLIED  -- reserved for possible future use --\n"
"  >\n"
"\n"
"<!ELEMENT NOSCRIPT - - (%flow;)*\n"
"  -- alternate content container for non script-based rendering -->\n"
"<!ATTLIST NOSCRIPT\n"
"  %attrs;                              -- %coreattrs, %i18n, %events --\n"
"  >\n"
"\n"
"<!--================ Document Structure ==================================-->\n"
"<!ENTITY % version \"version CDATA #FIXED '%HTML.Version;'\">\n"
"\n"
"<![ %HTML.Frameset; [\n"
"<!ENTITY % html.content \"HEAD, FRAMESET\">\n"
"]]>\n"
"\n"
"<!ENTITY % html.content \"HEAD, BODY\">\n"
"\n"
"<!ELEMENT HTML O O (%html.content;)    -- document root element -->\n"
"<!ATTLIST HTML\n"
"  %i18n;                               -- lang, dir --\n"
"  %version;\n"
"  >\n";


};	// namespace molib

// vim: ts=8 sw=8

