#!/bin/sh
#
# File:		dev/build-macosx
# Object:	Build the Mac OS/X installer
#
# Copyright:	Copyright (c) 2008 Made to Order Software Corp.
#
#		All Rights Reserved.
#
#		This software and its associated documentation contains
#		proprietary, confidential and trade secret information
#		of Made to Order Software Corp. and except as provided by
#		written agreement with Made to Order Software Corp.
#
#		a) no part may be disclosed, distributed, reproduced,
#		   transmitted, transcribed, stored in a retrieval system,
#		   adapted or translated in any form or by any means
#		   electronic, mechanical, magnetic, optical, chemical,
#		   manual or otherwise,
#
#		and
#
#		b) the recipient is not entitled to discover through reverse
#		   engineering or reverse compiling or other such techniques
#		   or processes the trade secrets contained therein or in the
#		   documentation.
#
set -e

#
# Use this script to build the Mac OS/X dmg file.
#

# This script cannot be used by itself, there is too much going on in
# the main script (dev/build)

if test -z "$BUILD_VERSION" -o -z "$BUILD_VERSION_STRING" -o -z "$VERSION"
then
	echo "turnwatcher: error: some environment variables defined by the dev/build script"
	echo "turnwatcher: error: are not defined; $0 cannot be used directly."
	exit 1;
fi



#
# Watch out! We need to take the $DEMO variable in account.
# At this time, the rest is pretty much the same all over otherwise.
#


BUILD_MACOSX=BUILD/macosx

mkdir -p $TMPDIR $BUILD_MACOSX



##
## Setup and make sure all the necessary variables
## are defined
##
if $DEMO || $BETA
then
	DEMO_WORD=" Demo"
else
	DEMO_WORD=
fi

MACOSX_VERSION=$VERSION-${BUILD_VERSION_STRING}_$DEMO_NAME


if test `uname -m` = "Power Macintosh"
then
	ARCH=ppc
else
	ARCH=i386
fi
OUTPUT=turnwatcher-install-$MACOSX_VERSION-darwin-$ARCH.exe



##
## Show the user the full version!
##
echo
echo "turnwatcher: building Turn Watcher version $MACOSX_VERSION"
echo "turnwatcher: for Mac OS/X arch in $BUILD_MACOSX"
echo "turnwatcher: output file: \"$OUTPUT\""
START_DATE=`date`
echo "turnwatcher: start date: $START_DATE"




# Delete any old version so we know whether we really get a new version
rm -rf $BUILD_MACOSX/turnwatcher-install-*[0-9].*[0-9]-*[0-9]_*[0-9]$DEMO_NAME-darwin-*.exe


SANDBOX_PREFIX=/usr/lib/mo/$CONFIGURE_MOVERSION




# Get ready to compile
export LANG=C
export LANGUAGE=C
export PATH="$SANDBOX_PREFIX/bin:$PATH"

export PKG_CONFIG_PATH=$SANDBOX_PREFIX/lib/pkgconfig
export LD_LIBRARY_PATH=$SANDBOX_PREFIX/lib



# install result in Applications
TW_PREFIX=${SANDBOX_PREFIX}/macosx

# compile in BUILD/macosx
cd BUILD/macosx


if $DEBUG
then
	dbg=--enable-debug
else
	dbg=
fi
if $BETA
then
	beta=--enable-beta
else
	beta=
fi
if $DEMO
then
	demo=--enable-demo
else
	demo=
fi
if $LEGACY_UI
then
	legacy_ui=--enable-legacyui
else
	legacy_ui=
fi

../../configure $demo $beta $dbg $legacy_ui \
	--enable-shared \
	--disable-static \
	--prefix=$TW_PREFIX

make
make install


echo "turnwatcher: the output of the ssh session is in $TMPDIR/build-macosx.txt"



#if test -d $PACKAGES_DIR
#then
#	cp -f $BUILD_MACOSX/$OUTPUT $PACKAGES_DIR/$OUTPUT
#
#	# If it is not the first time, the add will fail, but with -Q nothing is printed
#	if $CHECKIN_PACKAGES
#	then
#		(
#			svn --quiet add $PACKAGES_DIR/$OUTPUT
#			svn commit --non-interactive -N \
#				-m "Turn Watcher Mac OS/X -- automatic build on `date`" \
#				$PACKAGES_DIR/$OUTPUT
#		) >>$TMPDIR/build-win32.txt 2>&1
#	fi
#fi


echo "turnwatcher: end date: `date` (started on: $START_DATE)"
echo
echo "turnwatcher: build Mac OS/X finished."
echo



# vim: ts=8

