#!/bin/sh
#
# File:		dev/build-autoreconf
# Object:	Build the configure script & Co.
#
# Copyright:	Copyright (c) 2006-2008 Made to Order Software Corp.
#
#		All Rights Reserved.
#
#		This software and its associated documentation contains
#		proprietary, confidential and trade secret information
#		of Made to Order Software Corp. and except as provided by
#		written agreement with Made to Order Software Corp.
#
#		a) no part may be disclosed, distributed, reproduced,
#		   transmitted, transcribed, stored in a retrieval system,
#		   adapted or translated in any form or by any means
#		   electronic, mechanical, magnetic, optical, chemical,
#		   manual or otherwise,
#
#		and
#
#		b) the recipient is not entitled to discover through reverse
#		   engineering or reverse compiling or other such techniques
#		   or processes the trade secrets contained therein or in the
#		   documentation.
#

set -e

# We want to re-generate the configure script when building a master
# for Win32, Mac OS/X, Debian & the tarball.
# Make sure we have those built.

if test "`uname`" = "Darwin"
then
        export ACLOCAL="aclocal -I /opt/local/share/aclocal -I /usr/share/aclocal"
fi

if $VERBOSE
then
	autoreconf -f -i -v
else
	if $QUIET
	then
		mkdir -p $TMPDIR
		autoreconf -f -i >$TMPDIR/autoreconf.output 2>&1
	else
		autoreconf -f -i
	fi
fi


