#!/bin/sh
#
# File:		mainline/dev/build-tarball
# Object:	Build the tarball packages
#
# Copyright:	Copyright (c) 2006-2008 Made to Order Software Corp.
#
#		All Rights Reserved.
#
#		This software and its associated documentation contains
#		proprietary, confidential and trade secret information
#		of Made to Order Software Corp. and except as provided by
#		written agreement with Made to Order Software Corp.
#
#		a) no part may be disclosed, distributed, reproduced,
#		   transmitted, transcribed, stored in a retrieval system,
#		   adapted or translated in any form or by any means
#		   electronic, mechanical, magnetic, optical, chemical,
#		   manual or otherwise,
#
#		and
#
#		b) the recipient is not entitled to discover through reverse
#		   engineering or reverse compiling or other such techniques
#		   or processes the trade secrets contained therein or in the
#		   documentation.
#
# Log:
# Oct 23, 2006
# Created.
#
set -e

###
# The method to create the tarball is to first build the debian packages
# (in this script we assume that was already done) and then extract
# the files from the .deb and use tar to create the corresponding
# .tar.gz files.
###

# Get the options & version
. dev/get_options
. dev/get_version

ARCH=`uname -m`
case "$ARCH" in
i386|i686)
	ARCH=i386
	;;
x86_64)
	ARCH=amd64
	;;
*)
	echo "turnwatcher:error: unsupported architecture."
	exit 1
	;;
esac
OUTPUT=turnwatcher${DEMO_NAME}-${FULL_VERSION}_${ARCH}.tar.gz


# Make sure that the corresponding debian files are available
INPUT=turnwatcher${DEMO_NAME}_${FULL_VERSION}_${ARCH}.deb

if ! test  -f $PACKAGES_DIR/${INPUT}
then
	echo "turnwatcher: error: debian package ${INPUT} not found.";
	echo "turnwatcher: error: corresponding tarball package will not be created.";
	exit 1;
fi

MO_PKGLIBDIR="/usr/lib/mo/$CONFIGURE_MOVERSION"
GTK_VERSION=`cd $MO_PKGLIBDIR/lib/gtk-2.0; ls -d [1-9]*`
PANGO_VERSION=`cd $MO_PKGLIBDIR/lib/pango; ls -d [1-9]*`

EXTRA_NAME="`echo $DEMO_NAME | sed -e 's/-//'`"
if test -n "$EXTRA_NAME"
then
	EXTRA_NAME="${EXTRA_NAME}_"
fi

# Function to create one package
echo "turnwatcher: info: building the tarball (see tmp/tarball${DEMO_NAME}.output)"
(
	# Make sure that we regenerate from scratch
	rm -rf tmp/turnwatcher-${EXTRA_NAME}$FULL_VERSION
	mkdir -p tmp/turnwatcher-${EXTRA_NAME}$FULL_VERSION
	cd tmp/turnwatcher-${EXTRA_NAME}$FULL_VERSION

	# Extract files from .deb file
	ar x ../../$PACKAGES_DIR/$INPUT
	tar xzf data.tar.gz
	rm control.tar.gz debian-binary data.tar.gz

	# Add some stuff for tarball
	cp -p ../../debian/changelog ../../dev/linux/README .
	grep -v '^##.*' ../../dev/linux/install.sh.in \
		| sed -e "s/@MO_VERSION@/$CONFIGURE_MOVERSION/" \
			-e "s/@GTK_VERSION@/$GTK_VERSION/" \
			-e "s/@PANGO_VERSION@/$PANGO_VERSION/" >install.sh
	chmod 750 install.sh

	# Create tarball (directly where it needs to be)
	cd ..
	tar cvzf ../$PACKAGES_DIR/$OUTPUT --exclude=*turnwatcher-browser* turnwatcher-${EXTRA_NAME}$FULL_VERSION

	cd ..
) >tmp/tarball${DEMO_NAME}.output 2>&1



# Check whether it worked
if ! test -f $PACKAGES_DIR/$OUTPUT
then
	echo
	echo "turnwatcher: error: tarball ${OUTPUT} not rebuilt."
	echo "turnwatcher: error: look for why this happened and then try again."
	echo
	exit 1
fi


# If the person does not have the packages checked out it won't work
# correctly
if ! test -d $PACKAGES_DIR/.svn
then
	echo "turnwatcher: warning: it looks as if you did not have packages checked out."
	echo "turnwatcher: warning: this script cannot check in the new one until you do:"
	echo "turnwatcher: warning:    svn update packages/turnwatcher"
	# NOTE: this is wrong when in a sub-folder branch stuff as created by Doug...
	echo "turnwatcher: warning: under your 'sources' directory (`cd ../../../ && pwd`)."
	echo "turnwatcher: warning: the new packages can be found in ${PACKAGES_DIR}."
else
	# If it is not the first time, the add will fail, but with -Q nothing is printed
	if $CHECKIN_PACKAGES
	then
		echo "turnwatcher: info: checking-in the resulting tarball packages..."
		(
			svn --quiet add $PACKAGES_DIR/$OUTPUT
			svn commit --non-interactive -N \
					-m "Turn Watcher tarball -- automatic build on `date`" \
					$PACKAGES_DIR/$OUTPUT
		) >>$TMPDIR/build-tarball.txt 2>&1
	fi
fi




