#!/bin/sh
#
# File:		$Source: /mnt/cvs/root/m2osw/development/commercial/turnwatcher/mainline/dev/get_options,v $
# Object:	Do a complete build of the software package
# Version:	$Revision: 1.9 $
# Last Edit:	$Date: 2006/06/01 09:17:15 $
#
# Copyright:	Copyright (c) 2005-2006 Made to Order Software Corp.
#
#		All Rights Reserved.
#
#		This software and its associated documentation contains
#		proprietary, confidential and trade secret information
#		of Made to Order Software, Corp. and except as provided by
#		written agreement with Made to Order Software, Corp.
#
#		a) no part may be disclosed, distributed, reproduced,
#		   transmitted, transcribed, stored in a retrieval system,
#		   adapted or translated in any form or by any means
#		   electronic, mechanical, magnetic, optical, chemical,
#		   manual or otherwise,
#
#		and
#
#		b) the recipient is not entitled to discover through reverse
#		   engineering or reverse compiling or other such techniques
#		   or processes the trade secrets contained therein or in the
#		   documentation.
#
# $Id: get_options,v 1.9 2006/06/01 09:17:15 alexis Exp $
#
# $Log: get_options,v $
# Revision 1.13  2006/09/22 07:23:23  alexis
# Removed the BUILD_VERSION variable since it was using the old Alexis' version
# scheme (in a separate file). At this time we do not show what the last version
# was...
#
# Revision 1.12  2006/09/08 07:12:30  alexis
# Updated the help
# Added the --tarball option
#
# Revision 1.11  2006/08/28 04:14:52  alexis
# Removed the --build-dir option (and BUILD_DIR var)
#
# Revision 1.10  2006/08/21 00:05:06  alexis
# Added the --full-version option so we can see the full version in the
# get_version script
#
# Revision 1.9  2006/06/01 09:17:15  alexis
# Added support for --all to generate all the versions (full, beta, demo)
#
# Revision 1.8  2006/01/20 16:41:17  alexis
# Added the --cd and --download flags
#
# Revision 1.7  2006/01/14 11:35:36  alexis
# Fixed the --beta flag and check that both --demo & --beta aren't used together
#
# Revision 1.6  2005/12/30 17:50:56  alexis
# Added --beta & BUILD_VERSION and --no-package-checkin
#
# Revision 1.5  2005/12/29 22:26:03  alexis
# Moved packages one directory up so it is common to all versions...
#
# Revision 1.4  2005/12/24 06:47:31  alexis
# Added a few lines to automatically check in new versions as I build them
#
# Revision 1.3  2005/12/23 09:11:14  alexis
# Fixed the copyright (Corp.)
#
# Revision 1.2  2005/12/22 06:50:47  alexis
# First mostly working version. It goes up to compiling mo (thought I still
# have many header files missing).
#
# Revision 1.1  2005/12/20 19:58:56  alexis
# A start with the automated build system
#
#
#
#


#
# This script is called by all the other scripts to read the command line
#
#	. dev/get_options
#


# Make sure we do it only once
# (because all the scripts will call this one!)
if test "x$get_options" = "x"
then
	# "private" variables
	help=false
	get_options="done"


	# Initialize common variables
	ALL=false
	DEMO=false
	LEGACY_UI=true
	BETA=false
	DOWNLOAD_VERSION=false
	DEBIAN=false
	TARBALL=false
	REDHAT=false
	WIN32=false
	MACOSX=false
	DEBUG=false
	VERBOSE=false
	SHOW_FULL_VERSION=false
	if test -d ../../../packages
	then
		PACKAGES_DIR=../../../packages/turnwatcher
	elif test -d ../../../../packages
	then
		PACKAGES_DIR=../../../../packages/turnwatcher
	else
		echo "get_options: error: Sorry! I could not find the packages directory"
		exit 1;
	fi
	TMPDIR=tmp
	CHECKIN_PACKAGES=true
	QUIET=false

	while test "x$1" != "x"
	do
		case "$1" in
		-h*|--h*)       help=true;;
		--all)          ALL=true;;
		--full)         DEMO=false; BETA=false;;
		--demo)         DEMO=true;;
		--beta)         BETA=true;;
		--cd)           DOWNLOAD_VERSION=false;;
		--download)     DOWNLOAD_VERSION=true;;
		--all-arch)     DEBIAN=true; TARBALL=true; REDHAT=true; WIN32=true; MACOSX=true;;
		--debian)       DEBIAN=true;;
		--redhat)       REDHAT=true;;
		--win32)        WIN32=true;;
		--tarball)      TARBALL=true;;
		--macosx)       MACOSX=true;;
		--legacy-ui|--legacyui|--enable-legacyui) LEGACY_UI=true;;
		--debug)        DEBUG=true;;
		--quiet)	QUIET=true;;
		--verbose)      VERBOSE=true;;
		--full-version) SHOW_FULL_VERSION=true;;
		--no-package-checkin) CHECKIN_PACKAGES=false;;
		esac
		shift
	done


	if $help
	then
		echo "turnwatcher: dev/<scripts> [--opt] [filename]"
		echo "where --opt is one or more of the following:"
		echo "   -h or --help          show this help page"
		echo ""
		echo " Version:"
		echo "   --all                 build full, beta & demo versions (prevent --beta/--demo)"
		echo "   --full                build the full version (release; this is the default)"
		echo "   --demo                create the demo version (prevent --beta/--all)"
		echo "   --beta                create the beta version (prevent --demo/--all)"
		echo ""
		echo " Options:"
		echo "   --debug               build a debug version"
		echo "   --cd                  create a CD version (opposed to download--default)"
		echo "   --download            create a download version (opposed to a CD)"
		echo "   --all-arch            create binary for all architectures supported"
		echo "   --debian              create binary for Debian"
		echo "   --redhat              create binary for RedHat (implies --debian)"
		echo "   --win32               create binary for Win32"
		echo "   --tarball             create binary for Linux in a tarball (implies --debian)"
		echo "   --macosx              create binary for Mac OS/X"
		echo "   --legacy-ui           configure with --enable-legacyui (default)"
		echo "   --quiet               save output of autoreconf, configure, etc. in temp. files"
		echo "   --verbose             make the script more verbose"
		echo "   --full-version        print out the full version (dev/get_version)"
		echo "   --no-package-checkin  turn off auto-checking of packages at the end of a build"
		echo
		echo "turnwatcher: warning: script is stopping now."
		exit 1;
	fi

	bad=false
	if $BETA && $DEMO
	then
		bad=true
	fi
	if $BETA && $ALL
	then
		bad=true
	fi
	if $DEMO && $ALL
	then
		bad=true
	fi
	if $bad
	then
		echo "turnwatcher: error: cannot have --all, --beta and --demo at the same time"
		echo
		echo "turnwatcher: error: script is stopping now."
		exit 1;
	fi

	# --debian implied (makes scripts easier too!)
	# Actually redhat & tarball scripts do check the
	# availability of the debian files as required
	#if $REDHAT || $TARBALL
	#then
	#	DEBIAN=true
	#fi
fi

# vim: ts=8
