Document: turnwatcher
Title: Debian turnwatcher Manual
Author: <insert document author here>
Abstract: This manual describes what turnwatcher is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/turnwatcher/turnwatcher.sgml.gz

Format: postscript
Files: /usr/share/doc/turnwatcher/turnwatcher.ps.gz

Format: text
Files: /usr/share/doc/turnwatcher/turnwatcher.text.gz

Format: HTML
Index: /usr/share/doc/turnwatcher/html/index.html
Files: /usr/share/doc/turnwatcher/html/*.html
